/**
 * pdf-writer 单元测试。
 *
 * 覆盖：base14（/Helvetica + /WinAnsiEncoding）与嵌入 TrueType（/Type0 + /Identity-H + /CIDFontType2 +
 * /FontFile2 + /ToUnicode）两条渲染路径 / needsUnicodeFont 正反例 / PDF 文件结构（%PDF 头 + xref 表
 * 逐条偏移自校验 + trailer + startxref + %%EOF）/ 多页分页与 /Count 一致 / 表格渲染 / 输出确定性 /
 * 空文档 / `(` `)` `\` 转义 / 字体发现 / **字体子集化**（体积、SubsetStats、复合字形闭包、子集 sfnt
 * 结构自校验、subsetFont:false 回归、子集路径确定性、损坏字体安全回退）。
 *
 * 环境说明：本机（Windows）通常能发现 msyh.ttc，**需要 base14 路径的用例一律显式传 `font: null`**，
 * 否则 writePdf 会自动嵌入字体，断言就与机器环境耦合；需要嵌入路径的用例则用 discoverPdfFont()
 * 并在返回 null 时 t.skip()。复合字形闭包额外用**测试内自造的合成字体**验证，不依赖本机字体。
 *
 * 测试侧自带一套独立的 sfnt 解析器（表目录 / loca / glyf / 复合字形 component），
 * 不复用被测模块的内部实现，避免「用被测代码验证被测代码」。
 */
import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { inflateSync } from 'node:zlib';
import {
  discoverPdfFont,
  needsUnicodeFont,
  writePdf,
  type PdfDocSpec,
  type PdfFontInfo,
} from '../src/lib/artifacts/pdf-writer';

/* -------------------------------------------------------------------------- */
/* 测试辅助                                                                    */
/* -------------------------------------------------------------------------- */

/** 文本型断言用 latin1 解码（PDF 里的对象体是 ASCII / Latin-1）。 */
function asText(data: Buffer): string {
  return data.toString('latin1');
}

/** 从页对象字典里读 /Count（Pages 对象在文件头部，只解码前 64KB 足够）。 */
function declaredPageCount(data: Buffer): number {
  const head = asText(data.subarray(0, Math.min(data.length, 65536)));
  const match = /\/Type \/Pages[^>]*\/Count (\d+)/.exec(head);
  assert.ok(match !== null, 'PDF 必须包含带 /Count 的 /Type /Pages 对象');
  return Number.parseInt(match[1], 10);
}

/**
 * 结构校验：%PDF 头 / xref 表 / trailer / startxref / %%EOF，
 * 并且**逐条验证 xref 偏移确实指向对应对象头**（比只看关键字强得多）。
 */
function assertPdfStructure(data: Buffer): void {
  const text = asText(data);

  assert.ok(text.startsWith('%PDF-1.'), 'PDF 必须以 %PDF-1.x 开头');
  assert.ok(text.includes('xref'), 'PDF 必须含 xref 表');
  assert.ok(text.includes('trailer'), 'PDF 必须含 trailer');
  assert.ok(text.trimEnd().endsWith('%%EOF'), 'PDF 必须以 %%EOF 结尾');

  const startxrefIndex = text.lastIndexOf('startxref');
  assert.ok(startxrefIndex > 0, 'PDF 必须含 startxref');
  const offsetToken = text.slice(startxrefIndex + 'startxref'.length).trim().split(/\s+/)[0];
  const startxref = Number.parseInt(offsetToken, 10);
  assert.ok(Number.isInteger(startxref) && startxref > 0, 'startxref 必须是正整数偏移');
  assert.equal(text.slice(startxref, startxref + 4), 'xref', 'startxref 指向的偏移处必须是 xref');

  const header = /^xref\n0 (\d+)\n/.exec(text.slice(startxref));
  assert.ok(header !== null, 'xref 表头必须是 "xref\\n0 N\\n"');
  const count = Number.parseInt(header[1], 10);
  assert.ok(count >= 2, 'xref 至少应包含空闲条目 + 若干对象');
  const tableStart = startxref + header[0].length;
  for (let index = 1; index < count; index += 1) {
    const entry = text.slice(tableStart + index * 20, tableStart + index * 20 + 20);
    assert.equal(entry.length, 20, `xref 第 ${index} 条必须是固定 20 字节`);
    // 20 字节 = 10 位偏移 + 空格 + 5 位代数 + 空格 + 'n' + 2 字节行结束符
    assert.match(entry, /^\d{10} \d{5} n [\r\n]$/, `xref 第 ${index} 条格式不合法`);
    const objectOffset = Number.parseInt(entry.slice(0, 10), 10);
    const expected = `${index} 0 obj`;
    assert.equal(
      text.slice(objectOffset, objectOffset + expected.length),
      expected,
      `xref 第 ${index} 条的偏移没有指向对象头`,
    );
  }

  const trailer = text.slice(text.lastIndexOf('trailer'), text.lastIndexOf('trailer') + 200);
  assert.match(trailer, /\/Size \d+/, 'trailer 必须含 /Size');
  assert.match(trailer, /\/Root \d+ 0 R/, 'trailer 必须含 /Root');
}

function asciiDoc(): PdfDocSpec {
  return {
    title: 'Weekly Business Report',
    subtitle: 'Sichuan House · 2026-W37',
    sections: [
      {
        heading: 'Overview',
        paragraphs: ['Revenue reached $12,480 this week, up 8.3% week over week.'],
        bullets: ['Table turnover 3.2x per table', 'Complaint rate down to 1.8%'],
        table: {
          name: 'Category detail',
          columns: ['Category', 'Units', 'Revenue'],
          rows: [
            ['Signature', 320, '$4,800'],
            ['Drinks', 210, '$1,260'],
          ],
        },
      },
    ],
    footer: 'Generated by RoveFrame AI COO',
  };
}

function chineseDoc(): PdfDocSpec {
  return {
    title: '经营周报',
    subtitle: '四川人家 · 2026 年第 37 周',
    sections: [
      {
        heading: '一、总体经营情况',
        paragraphs: ['本周营业额 $12,480，环比上涨 8.3%，其中堂食占 71%、外卖占 29%。'],
        bullets: ['周末翻台率 3.2 次/桌', '差评率降至 1.8%'],
        table: {
          name: '品类销售明细',
          columns: ['品类', '销量', '收入'],
          rows: [
            ['招牌菜', 320, '$4,800'],
            ['饮品', 210, '$1,260'],
          ],
        },
      },
    ],
    footer: '由 RoveFrame AI COO 生成',
  };
}

/* -------------------------------------------------------------------------- */
/* needsUnicodeFont                                                            */
/* -------------------------------------------------------------------------- */

describe('needsUnicodeFont', () => {
  test('ASCII 与 Latin-1 文本不需要 Unicode 字体', () => {
    assert.equal(needsUnicodeFont(''), false);
    assert.equal(needsUnicodeFont('Revenue $12,480 - up 8.3%'), false);
    assert.equal(needsUnicodeFont('café résumé naïve'), false);
    assert.equal(needsUnicodeFont('“smart quotes” – dash • bullet €'), false);
    assert.equal(needsUnicodeFont('line one\nline two\ttabbed'), false);
  });

  test('CJK / emoji / 其他符号需要 Unicode 字体', () => {
    assert.equal(needsUnicodeFont('中文'), true);
    assert.equal(needsUnicodeFont('四川人家'), true);
    assert.equal(needsUnicodeFont('日本語のテキスト'), true);
    assert.equal(needsUnicodeFont('한국어'), true);
    assert.equal(needsUnicodeFont('🎉 emoji'), true);
    assert.equal(needsUnicodeFont('箭头 → 与全角付费'), true);
    assert.equal(needsUnicodeFont('mixed 中英文 text'), true);
  });

  test('C0 控制字符属于 ASCII 区，不算「缺字体」（排版时会被清掉）', () => {
    assert.equal(needsUnicodeFont('\u0000\u0001\u0007'), false);
    assert.equal(needsUnicodeFont('control \u001f char'), false);
  });
});

/* -------------------------------------------------------------------------- */
/* base14 路径                                                                 */
/* -------------------------------------------------------------------------- */

describe('writePdf / base14（font: null）', () => {
  test('纯 ASCII 内容生成成功且不需要 Unicode 字体', () => {
    const result = writePdf(asciiDoc(), { font: null });
    assert.equal(result.mime, 'application/pdf');
    assert.equal(result.ext, 'pdf');
    assert.equal(result.font, 'helvetica');
    assert.equal(result.fontPath, undefined);
    assert.equal(result.requiresUnicodeFont, false);
    assert.equal(result.pageCount, 1);
    assert.ok(result.data.length > 1000, 'PDF 不该是空壳');
    assertPdfStructure(result.data);

    const text = asText(result.data);
    assert.ok(text.includes('/Type1'), 'base14 路径必须用 /Type1 字体');
    assert.ok(text.includes('/Helvetica-Bold'), 'base14 路径的标题必须用 Helvetica-Bold');
    assert.ok(text.includes('/WinAnsiEncoding'), 'base14 路径必须声明 /WinAnsiEncoding');
    assert.ok(text.includes('(Weekly Business Report) Tj'), '文本必须以字面量写进内容流');
  });

  test('含中文但无字体：不抛错，requiresUnicodeFont 为 true', () => {
    const result = writePdf(chineseDoc(), { font: null });
    assert.equal(result.font, 'helvetica');
    assert.equal(result.requiresUnicodeFont, true);
    assert.equal(result.pageCount, 1);
    assertPdfStructure(result.data);
    assert.equal(declaredPageCount(result.data), result.pageCount);
  });

  test('font 指向不存在的文件时回落 base14（不抛错）', () => {
    const missing = 'Z:\\roveframe-no-such-dir\\no-such-font.ttf';
    const result = writePdf(chineseDoc(), {
      font: { path: missing, familyName: 'Nope', glyphCount: 1 },
    });
    assert.equal(result.font, 'helvetica');
    assert.equal(result.fontPath, undefined);
    assert.equal(result.requiresUnicodeFont, true);
    assertPdfStructure(result.data);
  });

  test('`(` `)` `\\` 与其它不可表示字符不破坏 PDF 结构', () => {
    const doc: PdfDocSpec = {
      title: 'Escaping (test) \\ backslash',
      sections: [
        {
          paragraphs: ['parens (a) and \\ backslash', 'deep ((())) and \\\\ done', 'control \u0001\u0002 char'],
        },
      ],
    };
    const result = writePdf(doc, { font: null });
    assert.equal(result.font, 'helvetica');
    assert.equal(result.requiresUnicodeFont, false);
    assertPdfStructure(result.data);

    const text = asText(result.data);
    assert.ok(
      text.includes('(parens \\(a\\) and \\\\ backslash) Tj'),
      '括号与反斜杠必须被转义成 \\( \\) \\\\',
    );
    assert.ok(text.includes('(deep \\(\\(\\(\\)\\)\\) and \\\\\\\\ done) Tj'), '连续括号同样要转义');
    // 两个相邻控制字符是同一个断行 token，因此输出 "control ?? char"（各自回落成 ?）
    assert.ok(text.includes('(control ?? char) Tj'), '不可打印字符应折叠为 ? 而不是写进内容流');
  });
});

/* -------------------------------------------------------------------------- */
/* 嵌入字体路径                                                                */
/* -------------------------------------------------------------------------- */

describe('writePdf / 嵌入 TrueType', () => {
  const font = discoverPdfFont();

  test('含中文 + 发现字体：Type0 / Identity-H / FontFile2 / ToUnicode 齐全', (t) => {
    if (font === null) {
      t.skip('本机未发现可用 TrueType 字体（discoverPdfFont() === null）');
      return;
    }
    const result = writePdf(chineseDoc(), { font });
    assert.equal(result.font, 'embedded');
    assert.equal(result.fontPath, font.path);
    assert.equal(result.requiresUnicodeFont, false, '嵌入字体后不应再要求调用方降级');
    assert.ok(result.pageCount >= 1);
    assertPdfStructure(result.data);

    assert.ok(result.data.includes('/Type0'), '嵌入路径必须声明 /Type0');
    assert.ok(result.data.includes('/Identity-H'), '嵌入路径必须用 /Identity-H 编码');
    assert.ok(result.data.includes('/CIDFontType2'), '嵌入路径必须是 /CIDFontType2');
    assert.ok(result.data.includes('/CIDToGIDMap /Identity'), 'CID 到 GID 必须是 Identity 映射');
    assert.ok(result.data.includes('/FontFile2'), '字体程序必须以 /FontFile2 内嵌');
    assert.ok(result.data.includes('/FlateDecode'), 'FontFile2 应使用 FlateDecode 压缩');
    assert.ok(result.data.includes('/ToUnicode'), '必须生成 ToUnicode CMap（可复制 / 可搜索）');
    assert.ok(result.data.includes('beginbfchar'), 'ToUnicode CMap 必须含 beginbfchar 映射');
    assert.ok(/\/W \[\s*\d+ \[/.test(asText(result.data)), '/W 必须是稀疏形式 [ gid [w...] ... ]');
    assert.ok(/<[0-9a-f]{4,}> Tj/.test(asText(result.data)), '文本必须写成 glyph id 十六进制串');
  });

  test('discoverPdfFont 的结果自洽，且 explicitPath 优先', (t) => {
    if (font === null) {
      t.skip('本机未发现可用 TrueType 字体');
      return;
    }
    assert.ok(font.glyphCount > 0, 'glyphCount 必须大于 0');
    assert.equal(typeof font.path, 'string');
    assert.ok(font.path.length > 0);
    assert.ok(font.familyName.trim().length > 0, 'familyName 不能为空');
    assert.ok(existsSync(font.path), '返回的路径必须真实存在');

    const explicit = discoverPdfFont(font.path);
    assert.ok(explicit !== null, '显式传入可用字体路径必须命中');
    assert.equal(explicit.path, font.path);
    assert.equal(explicit.glyphCount, font.glyphCount);

    const bogus = discoverPdfFont('Z:\\roveframe-no-such-dir\\no-such-font.ttf');
    if (bogus !== null) {
      assert.ok(existsSync(bogus.path), '显式路径失败后应继续找系统字体，而不是返回假路径');
    }
  });

  test('嵌入路径下 emoji / 控制字符 / 缺字不会崩（回落 .notdef）', (t) => {
    if (font === null) {
      t.skip('本机未发现可用 TrueType 字体');
      return;
    }
    const doc: PdfDocSpec = {
      title: '边界字符测试 🎉 \u0000\u0007',
      sections: [{ paragraphs: ['中文 + emoji 🚀 + 罕见字 𠮷 + 控制符 \u0001', 'x'.repeat(400)] }],
    };
    const result = writePdf(doc, { font });
    assert.equal(result.font, 'embedded');
    assertPdfStructure(result.data);
    assert.ok(result.pageCount >= 1);
  });
});

/* -------------------------------------------------------------------------- */
/* 结构与分页                                                                  */
/* -------------------------------------------------------------------------- */

describe('writePdf / 结构与分页', () => {
  test('空文档不抛错且至少一页', () => {
    const result = writePdf({ sections: [] }, { font: null });
    assert.equal(result.pageCount, 1);
    assert.equal(result.font, 'helvetica');
    assert.equal(result.requiresUnicodeFont, false);
    assertPdfStructure(result.data);
    assert.equal(declaredPageCount(result.data), 1);
  });

  test('只有标题 / 只有页脚也不抛错', () => {
    const onlyTitle = writePdf({ title: 'Title only', sections: [] }, { font: null });
    const onlyFooter = writePdf({ sections: [], footer: 'Generated by RoveFrame AI COO' }, { font: null });
    assert.equal(onlyTitle.pageCount, 1);
    assert.equal(onlyFooter.pageCount, 1);
    assertPdfStructure(onlyTitle.data);
    assertPdfStructure(onlyFooter.data);
  });

  test('300 段长文本自动分页，且 /Count 与 pageCount 一致', () => {
    const paragraphs = Array.from(
      { length: 300 },
      (_, index) => `第 ${index + 1} 条经营分析：本周该品类营业额环比上涨 8.3%，建议下周继续加大投放力度并关注库存周转天数。`,
    );
    const result = writePdf({ title: '长报告', sections: [{ heading: '明细', paragraphs }] }, { font: null });
    assert.ok(result.pageCount > 1, `300 段长文本应产生多页，实际 ${result.pageCount}`);
    assertPdfStructure(result.data);
    assert.equal(declaredPageCount(result.data), result.pageCount);
  });

  test('中文长段落按字宽换行（中文没有空格，不能按词断行）', () => {
    const paragraph = '经营分析'.repeat(150); // 600 个汉字，远超一行
    const result = writePdf({ sections: [{ paragraphs: [paragraph] }] }, { font: null });
    const text = asText(result.data);
    const lineCount = text.match(/\) Tj/g)?.length ?? 0;
    assert.ok(lineCount >= 5, `600 个汉字应折成多行，实际只有 ${lineCount} 行`);
    // 每行长度必须受页面宽度约束（内容宽 483.28pt，11pt 的 '?' 宽 6.116pt）
    for (const match of text.matchAll(/\((\?+)\) Tj/g)) {
      assert.ok(match[1].length <= 80, `单行 ${match[1].length} 个字符，超出行宽约束`);
    }
  });

  test('超长无空格单词被强制切分而不溢出', () => {
    // 'W' 在 Helvetica 里是 944/1000 em：11pt → 10.384pt；内容宽 483.28pt → 每行正好 46 个
    const charsPerLine = 46;
    const result = writePdf({ sections: [{ paragraphs: ['W'.repeat(charsPerLine * 30)] }] }, { font: null });
    assertPdfStructure(result.data);
    const lines = [...asText(result.data).matchAll(/\((W+)\) Tj/g)].map((match) => match[1].length);
    assert.equal(lines.length, 30, '1380 个连续字符应被切成 30 行');
    assert.ok(
      lines.every((length) => length === charsPerLine),
      `每行都应是 ${charsPerLine} 个字符，实际 ${lines.join(',')}`,
    );
  });
});

/* -------------------------------------------------------------------------- */
/* 表格                                                                        */
/* -------------------------------------------------------------------------- */

describe('writePdf / 表格', () => {
  test('columns + rows 渲染不抛错且页数 >= 1', () => {
    const result = writePdf(
      {
        title: '表格测试',
        sections: [
          {
            heading: '品类',
            table: {
              name: '明细',
              columns: ['品类', '销量', '收入', '备注'],
              rows: [
                ['招牌菜', 320, '$4,800', '热销'],
                ['饮品', 210, '$1,260', null],
                ['甜点', 96, '$576', true],
              ],
            },
          },
        ],
      },
      { font: null },
    );
    assert.ok(result.pageCount >= 1);
    assertPdfStructure(result.data);
    assert.equal(declaredPageCount(result.data), result.pageCount);
    const text = asText(result.data);
    assert.ok(text.includes('re S'), '表格必须画单元格边框');
    assert.ok(text.includes('re f'), '表头必须有浅灰底填充');
  });

  test('空表格 / 无列定义 / 畸形行不抛错', () => {
    const result = writePdf(
      {
        sections: [
          { heading: 'A', table: { columns: [], rows: [['x']] } },
          { heading: 'B', table: { columns: ['a', 'b'], rows: [] } },
          { heading: 'C', table: { name: 'only name', columns: ['a'], rows: [[]] } },
        ],
      },
      { font: null },
    );
    assert.ok(result.pageCount >= 1);
    assertPdfStructure(result.data);
  });

  test('长表格跨页时表头在新页重复', () => {
    const rows = Array.from({ length: 60 }, (_, index) => [`第 ${index + 1} 行`, index, `$${index * 10}`]);
    const result = writePdf(
      { sections: [{ table: { columns: ['名称', '数量', '金额'], rows } }] },
      { font: null },
    );
    assert.ok(result.pageCount > 1, `60 行表格应跨页，实际 ${result.pageCount} 页`);
    assertPdfStructure(result.data);
    assert.equal(declaredPageCount(result.data), result.pageCount);
    const text = asText(result.data);
    const headerFills = text.match(/0\.92 g/g)?.length ?? 0;
    assert.equal(headerFills, result.pageCount, '每一页都应重复一次表头（浅灰底填充）');
  });
});

/* -------------------------------------------------------------------------- */
/* 确定性与页脚                                                                */
/* -------------------------------------------------------------------------- */

describe('writePdf / 确定性与页脚', () => {
  test('同样输入两次调用输出完全一致（base14）', () => {
    const first = writePdf(chineseDoc(), { font: null, watermark: 'Generated by RoveFrame AI COO' });
    const second = writePdf(chineseDoc(), { font: null, watermark: 'Generated by RoveFrame AI COO' });
    assert.equal(Buffer.compare(first.data, second.data), 0, 'base14 路径必须字节确定');
  });

  test('同样输入两次调用输出完全一致（嵌入字体）', (t) => {
    const font = discoverPdfFont();
    if (font === null) {
      t.skip('本机未发现可用 TrueType 字体');
      return;
    }
    const first = writePdf(chineseDoc(), { font });
    const second = writePdf(chineseDoc(), { font });
    assert.equal(Buffer.compare(first.data, second.data), 0, '嵌入路径必须字节确定');
  });

  test('页脚含页码；watermark 额外写到页脚中间', () => {
    const result = writePdf(
      { title: 'Footer', sections: [{ paragraphs: ['body'] }], footer: 'RoveFrame footer' },
      { font: null, watermark: 'WATERMARK' },
    );
    const text = asText(result.data);
    assert.ok(text.includes('(RoveFrame footer) Tj'), 'doc.footer 必须写进页脚');
    assert.ok(text.includes('(WATERMARK) Tj'), 'watermark 必须写进页脚');
    assert.ok(text.includes('(1 / 1) Tj'), '页脚必须含页码');
  });

  test('多页时每页都有页码（N / total）', () => {
    const paragraphs = Array.from({ length: 200 }, (_, index) => `第 ${index + 1} 段：经营分析内容。`);
    const result = writePdf({ title: 'Paged', sections: [{ paragraphs }] }, { font: null });
    assert.ok(result.pageCount > 1);
    const text = asText(result.data);
    for (let page = 1; page <= result.pageCount; page += 1) {
      assert.ok(
        text.includes(`(${page} / ${result.pageCount}) Tj`),
        `第 ${page} 页缺少页码 "${page} / ${result.pageCount}"`,
      );
    }
  });
});

/* -------------------------------------------------------------------------- */
/* 输入健壮性                                                                  */
/* -------------------------------------------------------------------------- */

describe('writePdf / 输入健壮性', () => {
  test('完全畸形但类型合法的输入不抛错', () => {
    const weird: PdfDocSpec = {
      title: '   ',
      subtitle: '',
      sections: [
        { heading: '  ', paragraphs: ['', '   ', '\n\n'], bullets: ['', 'ok'] },
        { paragraphs: ['no heading'], table: { name: '', columns: ['c'], rows: [['v']] } },
      ],
      footer: '   ',
    };
    const result = writePdf(weird, { font: null });
    assert.ok(result.pageCount >= 1);
    assertPdfStructure(result.data);
  });

  test('emoji + 控制字符（base14）不抛错且标记需要 Unicode 字体', () => {
    const result = writePdf(
      { title: '🎉 派对', sections: [{ paragraphs: ['\u0000\u0001\u0002 \u2028 \uFFFD'] }] },
      { font: null },
    );
    assert.equal(result.requiresUnicodeFont, true);
    assertPdfStructure(result.data);
  });
});

/* -------------------------------------------------------------------------- */
/* 子集化：测试侧独立的 sfnt 解析器                                             */
/* -------------------------------------------------------------------------- */

interface SfntTableRecord {
  tag: string;
  checksum: number;
  offset: number;
  length: number;
}

interface TestSfnt {
  data: Buffer;
  records: SfntTableRecord[];
  numGlyphs: number;
  indexToLocFormat: number;
  /** numGlyphs + 1 个 glyf 偏移（已按 format 换算成字节） */
  loca: number[];
  glyfOffset: number;
  glyfLength: number;
}

/** 逐位独立的 sfnt 累加校验和（末尾不足 4 字节按 0 补齐）。 */
function testChecksum(data: Buffer): number {
  const padded = data.length % 4 === 0 ? data : Buffer.concat([data, Buffer.alloc(4 - (data.length % 4))]);
  let sum = 0;
  for (let i = 0; i < padded.length; i += 4) sum = (sum + padded.readUInt32BE(i)) % 4294967296;
  return sum;
}

function parseTestSfnt(data: Buffer): TestSfnt {
  assert.equal(data.readUInt32BE(0), 0x00010000, '字体程序必须是 sfnt version 1.0');
  const numTables = data.readUInt16BE(4);
  const records: SfntTableRecord[] = [];
  const byTag = new Map<string, SfntTableRecord>();
  for (let i = 0; i < numTables; i += 1) {
    const record = 12 + i * 16;
    const entry: SfntTableRecord = {
      tag: data.toString('latin1', record, record + 4),
      checksum: data.readUInt32BE(record + 4),
      offset: data.readUInt32BE(record + 8),
      length: data.readUInt32BE(record + 12),
    };
    records.push(entry);
    byTag.set(entry.tag, entry);
  }
  const lookup = (tag: string): SfntTableRecord => {
    const entry = byTag.get(tag);
    assert.ok(entry !== undefined, `字体程序缺少 ${tag} 表`);
    return entry;
  };
  const head = lookup('head');
  const maxp = lookup('maxp');
  const loca = lookup('loca');
  const glyf = lookup('glyf');
  const numGlyphs = data.readUInt16BE(maxp.offset + 4);
  const indexToLocFormat = data.readInt16BE(head.offset + 50);
  assert.ok(indexToLocFormat === 0 || indexToLocFormat === 1, 'indexToLocFormat 必须是 0 或 1');
  const entrySize = indexToLocFormat === 0 ? 2 : 4;
  assert.equal(loca.length, (numGlyphs + 1) * entrySize, 'loca 条目数必须 = numGlyphs + 1');
  const locaOffsets: number[] = [];
  for (let gid = 0; gid <= numGlyphs; gid += 1) {
    locaOffsets.push(
      indexToLocFormat === 0 ? data.readUInt16BE(loca.offset + gid * 2) * 2 : data.readUInt32BE(loca.offset + gid * 4),
    );
  }
  return { data, records, numGlyphs, indexToLocFormat, loca: locaOffsets, glyfOffset: glyf.offset, glyfLength: glyf.length };
}

/** 从 PDF 里取出 /FontFile2 流并解 FlateDecode。 */
function extractFontFile2(pdf: Buffer): Buffer {
  const marker = pdf.indexOf('/FontFile2');
  assert.ok(marker > 0, 'PDF 必须含 /FontFile2');
  const dictStart = pdf.indexOf('/Length1 ', marker);
  assert.ok(dictStart > marker, '/FontFile2 对象必须带 /Length1');
  const dict = pdf.toString('latin1', dictStart, dictStart + 240);
  const match = /\/Length1 (\d+) \/Filter \/FlateDecode \/Length (\d+) >>\nstream\n/.exec(dict);
  assert.ok(match !== null, 'FontFile2 字典格式不符合预期');
  const streamStart = dictStart + match.index + match[0].length;
  const raw = inflateSync(pdf.subarray(streamStart, streamStart + Number.parseInt(match[2], 10)));
  assert.equal(raw.length, Number.parseInt(match[1], 10), '/Length1 必须等于解压后的字体程序长度');
  return raw;
}

function parseSubset(pdf: Buffer): TestSfnt {
  return parseTestSfnt(extractFontFile2(pdf));
}

/** 子集里非空（有轮廓数据）的 gid 集合。 */
function presentGlyphs(sfnt: TestSfnt): Set<number> {
  const present = new Set<number>();
  for (let gid = 0; gid < sfnt.numGlyphs; gid += 1) {
    if (sfnt.loca[gid + 1] > sfnt.loca[gid]) present.add(gid);
  }
  return present;
}

function glyphIsComposite(sfnt: TestSfnt, gid: number): boolean {
  if (sfnt.loca[gid + 1] <= sfnt.loca[gid]) return false;
  return sfnt.data.readInt16BE(sfnt.glyfOffset + sfnt.loca[gid]) < 0;
}

/** 复合字形的 component gid 列表（按 flag 累加 component 长度，直到 MORE_COMPONENTS 清零）。 */
function glyphComponents(sfnt: TestSfnt, gid: number): number[] {
  const start = sfnt.glyfOffset + sfnt.loca[gid];
  const end = sfnt.glyfOffset + Math.min(sfnt.loca[gid + 1], sfnt.glyfLength);
  const components: number[] = [];
  let offset = start + 10;
  while (offset + 4 <= end) {
    const flags = sfnt.data.readUInt16BE(offset);
    components.push(sfnt.data.readUInt16BE(offset + 2));
    offset += 4;
    offset += (flags & 0x0001) !== 0 ? 4 : 2;
    if ((flags & 0x0008) !== 0) offset += 2;
    else if ((flags & 0x0040) !== 0) offset += 4;
    else if ((flags & 0x0080) !== 0) offset += 8;
    if ((flags & 0x0020) === 0) break;
  }
  return components;
}

/** 内容流里写出的 glyph id（嵌入路径的 `<0048...> Tj`；只看字体对象之前的部分，避开二进制流误匹配）。 */
function usedGlyphsFromPdf(pdf: Buffer): Set<number> {
  const fontSection = pdf.indexOf('/Type0');
  const text = pdf.toString('latin1', 0, fontSection > 0 ? fontSection : pdf.length);
  const used = new Set<number>();
  for (const match of text.matchAll(/<([0-9a-f]+)> Tj/g)) {
    for (let i = 0; i + 4 <= match[1].length; i += 4) {
      used.add(Number.parseInt(match[1].slice(i, i + 4), 16));
    }
  }
  assert.ok(used.size > 0, '内容流里必须能读到 glyph id');
  return used;
}

/** 子集 sfnt 结构自校验：tag 升序 / 偏移对齐 / 每表 checkSum / 整文件 checkSum / loca 与 maxp、head 一致。 */
function assertSubsetSfntStructure(sfnt: TestSfnt): void {
  const tags = sfnt.records.map((record) => record.tag);
  assert.deepEqual(tags, [...tags].sort(), 'sfnt 表必须按 tag 升序排列');
  assert.ok(tags.includes('glyf') && tags.includes('loca') && tags.includes('maxp') && tags.includes('head'));

  for (const record of sfnt.records) {
    assert.equal(record.offset % 4, 0, `${record.tag} 表偏移必须 4 字节对齐`);
    assert.ok(record.offset + record.length <= sfnt.data.length, `${record.tag} 表超出文件范围`);
    const tableData = Buffer.from(sfnt.data.subarray(record.offset, record.offset + record.length));
    if (record.tag === 'head') tableData.writeUInt32BE(0, 8); // head 的 checkSum 按 checkSumAdjustment = 0 计算
    assert.equal(testChecksum(tableData), record.checksum, `${record.tag} 表 checkSum 不匹配`);
  }

  assert.equal(testChecksum(sfnt.data), 0xb1b0afba, '整文件 checkSum 必须等于 0xB1B0AFBA（checkSumAdjustment 正确回填）');

  for (let gid = 0; gid < sfnt.numGlyphs; gid += 1) {
    assert.ok(sfnt.loca[gid + 1] >= sfnt.loca[gid], `loca[${gid}] 必须单调不减`);
  }
  assert.equal(sfnt.loca[sfnt.numGlyphs], sfnt.glyfLength, 'loca 最后一项必须等于 glyf 表长度');
  assert.equal(sfnt.glyfLength % 2, 0, 'short loca 要求 glyf 长度为偶数');
}

/* -------------------------------------------------------------------------- */
/* 子集化：测试内自造的合成字体（不依赖本机装了什么字体）                        */
/* -------------------------------------------------------------------------- */

/** 一个合法的最小简单字形（三角形轮廓，3 个点）。 */
function buildSimpleGlyph(): Buffer {
  const data = Buffer.alloc(10 + 2 + 2 + 3 + 3 + 3);
  data.writeInt16BE(1, 0); // numberOfContours
  data.writeInt16BE(0, 2); // xMin
  data.writeInt16BE(0, 4); // yMin
  data.writeInt16BE(200, 6); // xMax
  data.writeInt16BE(200, 8); // yMax
  data.writeUInt16BE(2, 10); // endPtsOfContours[0] = 2（3 个点）
  data.writeUInt16BE(0, 12); // instructionLength
  data.writeUInt8(0x37, 14); // flags: ON_CURVE | X_SHORT | Y_SHORT | 正方向
  data.writeUInt8(0x37, 15);
  data.writeUInt8(0x37, 16);
  data.writeUInt8(0, 17); // x delta
  data.writeUInt8(200, 18);
  data.writeUInt8(0, 19);
  data.writeUInt8(0, 20); // y delta
  data.writeUInt8(0, 21);
  data.writeUInt8(200, 22);
  return data;
}

interface ComponentSpec {
  gid: number;
  /** flags 低位按 glyf 规范自行组合：0x0001 words / 0x0002 xy / 0x0008 scale / 0x0040 xy-scale / 0x0080 2x2 / 0x0020 more */
  flags: number;
}

/** 复合字形：把若干 component 拼起来（覆盖 byte/word args、scale、2x2、MORE_COMPONENTS 各分支）。 */
function buildCompositeGlyph(components: ComponentSpec[]): Buffer {
  const chunks: Buffer[] = [];
  const header = Buffer.alloc(10);
  header.writeInt16BE(-1, 0); // numberOfContours < 0 → 复合字形
  header.writeInt16BE(0, 2);
  header.writeInt16BE(0, 4);
  header.writeInt16BE(400, 6);
  header.writeInt16BE(400, 8);
  chunks.push(header);

  components.forEach((component, index) => {
    const isLast = index === components.length - 1;
    const flags = (component.flags & ~0x0020) | (isLast ? 0 : 0x0020);
    const entry = Buffer.alloc(4 + ((flags & 0x0001) !== 0 ? 4 : 2) + ((flags & 0x0008) !== 0 ? 2 : 0) + ((flags & 0x0040) !== 0 ? 4 : 0) + ((flags & 0x0080) !== 0 ? 8 : 0));
    entry.writeUInt16BE(flags, 0);
    entry.writeUInt16BE(component.gid, 2);
    chunks.push(entry);
  });
  return Buffer.concat(chunks);
}

function buildTestTable(tag: string, data: Buffer): { tag: string; data: Buffer } {
  return { tag, data };
}

/** 组装一个最小但合法的 sfnt（测试侧独立实现，与被测模块无关）。 */
function buildFixtureSfnt(tables: Array<{ tag: string; data: Buffer }>): Buffer {
  const sorted = [...tables].sort((a, b) => (a.tag < b.tag ? -1 : a.tag > b.tag ? 1 : 0));
  const header = Buffer.alloc(12);
  header.writeUInt32BE(0x00010000, 0);
  header.writeUInt16BE(sorted.length, 4);
  const entrySelector = Math.floor(Math.log2(sorted.length));
  const searchRange = 16 * 2 ** entrySelector;
  header.writeUInt16BE(searchRange, 6);
  header.writeUInt16BE(entrySelector, 8);
  header.writeUInt16BE(sorted.length * 16 - searchRange, 10);

  const directory = Buffer.alloc(sorted.length * 16);
  const chunks: Buffer[] = [header, directory];
  let offset = 12 + sorted.length * 16;
  let headOffset = -1;
  sorted.forEach((table, index) => {
    let data = table.data;
    if (table.tag === 'head') {
      data = Buffer.from(data);
      data.writeUInt32BE(0, 8);
      headOffset = offset;
    }
    const record = index * 16;
    directory.write(table.tag, record, 4, 'latin1');
    directory.writeUInt32BE(testChecksum(data), record + 4);
    directory.writeUInt32BE(offset, record + 8);
    directory.writeUInt32BE(data.length, record + 12);
    const padding = (4 - (data.length % 4)) % 4;
    const padded = padding > 0 ? Buffer.concat([data, Buffer.alloc(padding)]) : data;
    chunks.push(padded);
    offset += padded.length;
  });

  const file = Buffer.concat(chunks);
  if (headOffset >= 0) file.writeUInt32BE((0xb1b0afba - testChecksum(file)) >>> 0, headOffset + 8);
  return file;
}

/**
 * 造一个 5 字形的测试字体：
 * gid0 = .notdef（简单）、gid1 = 'A'（简单）、gid2 = 'B'（复合 → 1 + 3）、
 * gid3 = 'C'（简单，只被复合引用）、gid4 = 'D'（复合 → 2 再套 1，即嵌套复合）。
 * cmap 只映射 'A'..'D' → gid 1..4。
 * brokenLoca = true 时把 loca 指向 glyf 之外，用于验证子集化失败后的安全回退。
 */
function buildCompositeFixture(brokenLoca = false): Buffer {
  const simple = buildSimpleGlyph();
  const glyphs = [
    simple, // 0 .notdef
    simple, // 1 A
    buildCompositeGlyph([
      { gid: 1, flags: 0x0002 }, // byte args + MORE_COMPONENTS
      { gid: 3, flags: 0x0002 },
    ]), // 2 B
    simple, // 3 C（仅作为组件出现）
    buildCompositeGlyph([
      { gid: 2, flags: 0x0001 | 0x0002 | 0x0080 }, // word args + TWO_BY_TWO + MORE_COMPONENTS
      { gid: 1, flags: 0x0001 | 0x0002 | 0x0008 }, // word args + SCALE，最后一个
    ]), // 4 D
  ];

  const glyphChunks: Buffer[] = [];
  const loca: number[] = [];
  let glyfLength = 0;
  for (const glyph of glyphs) {
    loca.push(glyfLength);
    let padded = glyph;
    const padding = (4 - (glyph.length % 4)) % 4;
    if (padding > 0) padded = Buffer.concat([glyph, Buffer.alloc(padding)]);
    glyphChunks.push(padded);
    glyfLength += padded.length;
  }
  loca.push(glyfLength);
  if (brokenLoca) loca[2] = glyfLength + 4096; // gid1 的起点越界 → 子集化必须抛错并回退
  const glyf = Buffer.concat(glyphChunks, glyfLength);

  const locaTable = Buffer.alloc(loca.length * 4);
  loca.forEach((value, index) => locaTable.writeUInt32BE(value, index * 4));

  const head = Buffer.alloc(54);
  head.writeUInt32BE(0x00010000, 0);
  head.writeUInt32BE(0x00010000, 4);
  head.writeUInt32BE(0x5f0f3cf5, 12);
  head.writeUInt16BE(1000, 18); // unitsPerEm
  head.writeInt16BE(0, 36);
  head.writeInt16BE(-200, 38);
  head.writeInt16BE(400, 40);
  head.writeInt16BE(400, 42);
  head.writeInt16BE(1, 50); // indexToLocFormat = long

  const hhea = Buffer.alloc(36);
  hhea.writeUInt32BE(0x00010000, 0);
  hhea.writeInt16BE(800, 4);
  hhea.writeInt16BE(-200, 6);
  hhea.writeUInt16BE(glyphs.length, 34); // numberOfHMetrics

  const maxp = Buffer.alloc(32);
  maxp.writeUInt32BE(0x00010000, 0);
  maxp.writeUInt16BE(glyphs.length, 4);

  const hmtx = Buffer.alloc(glyphs.length * 4);
  for (let gid = 0; gid < glyphs.length; gid += 1) {
    hmtx.writeUInt16BE(600, gid * 4);
    hmtx.writeInt16BE(0, gid * 4 + 2);
  }

  // cmap：格式 4，一段 [0x41,0x44] → gid 1..4，加 0xFFFF 终止段
  const cmapSub = Buffer.alloc(32);
  cmapSub.writeUInt16BE(4, 0); // format
  cmapSub.writeUInt16BE(32, 2); // length
  cmapSub.writeUInt16BE(0, 4); // language
  cmapSub.writeUInt16BE(4, 6); // segCountX2
  cmapSub.writeUInt16BE(4, 8);
  cmapSub.writeUInt16BE(1, 10);
  cmapSub.writeUInt16BE(0, 12);
  cmapSub.writeUInt16BE(0x44, 14); // endCode[0]
  cmapSub.writeUInt16BE(0xffff, 16); // endCode[1]
  cmapSub.writeUInt16BE(0, 18); // reservedPad
  cmapSub.writeUInt16BE(0x41, 20); // startCode[0]
  cmapSub.writeUInt16BE(0xffff, 22); // startCode[1]
  cmapSub.writeInt16BE(1 - 0x41, 24); // idDelta[0]
  cmapSub.writeInt16BE(1, 26); // idDelta[1]
  cmapSub.writeUInt16BE(0, 28); // idRangeOffset[0]
  cmapSub.writeUInt16BE(0, 30); // idRangeOffset[1]
  const cmap = Buffer.concat([Buffer.alloc(12), cmapSub]);
  cmap.writeUInt16BE(0, 0);
  cmap.writeUInt16BE(1, 2);
  cmap.writeUInt16BE(3, 4); // platformID
  cmap.writeUInt16BE(1, 6); // encodingID
  cmap.writeUInt32BE(12, 8); // 子表偏移

  const family = Buffer.from('RoveTestFixture', 'utf16le');
  const nameRecord = Buffer.alloc(12);
  nameRecord.writeUInt16BE(3, 0);
  nameRecord.writeUInt16BE(1, 2);
  nameRecord.writeUInt16BE(0x409, 4);
  nameRecord.writeUInt16BE(1, 6); // nameID 1 = family
  nameRecord.writeUInt16BE(family.length, 8);
  nameRecord.writeUInt16BE(0, 10);
  const nameHeader = Buffer.alloc(6);
  nameHeader.writeUInt16BE(0, 0);
  nameHeader.writeUInt16BE(1, 2);
  nameHeader.writeUInt16BE(6 + 12, 4); // stringOffset
  for (let i = 0; i < family.length; i += 2) {
    const swap = family[i];
    family[i] = family[i + 1];
    family[i + 1] = swap;
  }
  const name = Buffer.concat([nameHeader, nameRecord, family]);

  return buildFixtureSfnt([
    buildTestTable('cmap', cmap),
    buildTestTable('glyf', glyf),
    buildTestTable('head', head),
    buildTestTable('hhea', hhea),
    buildTestTable('hmtx', hmtx),
    buildTestTable('loca', locaTable),
    buildTestTable('maxp', maxp),
    buildTestTable('name', name),
  ]);
}

function writeFixtureFont(name: string, data: Buffer): PdfFontInfo {
  const file = path.join(os.tmpdir(), `roveframe-pdf-fixture-${name}.ttf`);
  writeFileSync(file, data);
  return { path: file, familyName: 'RoveTestFixture', glyphCount: 5 };
}

/* -------------------------------------------------------------------------- */
/* 子集化                                                                      */
/* -------------------------------------------------------------------------- */

/** 多页中文文档：用来对比子集化前后的体积。 */
function longChineseDoc(): PdfDocSpec {
  const paragraphs = Array.from(
    { length: 40 },
    (_, index) =>
      `第 ${index + 1} 条经营分析：本周该品类营业额环比上涨 8.3%，建议下周继续加大投放力度并关注库存周转天数与毛利率变化。`,
  );
  return {
    title: '2026 年第 37 周经营分析报告',
    subtitle: '四川人家 · 由 RoveFrame AI COO 自动生成',
    sections: [
      { heading: '一、总体经营情况', paragraphs, bullets: ['周末翻台率 3.2 次/桌', '差评率降至 1.8%'] },
      {
        heading: '二、品类销售明细',
        table: {
          name: '明细',
          columns: ['品类', '销量', '收入', '环比'],
          rows: [
            ['招牌菜', 320, '$4,800', '+12.5%'],
            ['饮品', 210, '$1,260', '-3.2%'],
            ['甜点', 96, '$576', '+7.0%'],
          ],
        },
      },
    ],
    footer: '四川人家 · 经营周报',
  };
}

describe('writePdf / 字体子集化', () => {
  const font = discoverPdfFont();

  test('中文多页文档：子集化后 < 1.5MB，且远小于整份嵌入', (t) => {
    if (font === null) {
      t.skip('本机未发现可用 TrueType 字体');
      return;
    }
    const doc = longChineseDoc();
    const subsetOn = writePdf(doc, { font, subsetFont: true });
    const subsetOff = writePdf(doc, { font, subsetFont: false });

    assert.ok(subsetOn.pageCount > 1, '这份文档应该是多页的');
    assert.ok(subsetOn.subset !== null, 'subsetsOn 必须返回 SubsetStats');
    assert.ok(
      subsetOn.data.length < 1_500_000,
      `子集化后必须 < 1.5MB，实际 ${(subsetOn.data.length / 1024 / 1024).toFixed(2)}MB`,
    );
    assert.ok(
      subsetOn.data.length * 3 < subsetOff.data.length,
      `子集化体积必须远小于整份嵌入（${subsetOn.data.length} vs ${subsetOff.data.length}）`,
    );
    assertPdfStructure(subsetOn.data);
    assertPdfStructure(subsetOff.data);
    // 两条路径都仍走 Type0 + FontFile2 + ToUnicode
    for (const pdf of [subsetOn.data, subsetOff.data]) {
      assert.ok(pdf.includes('/Type0') && pdf.includes('/FontFile2') && pdf.includes('/ToUnicode'));
    }
  });

  test('SubsetStats 数字合理：只保留少量字形且字体程序大幅缩小', (t) => {
    if (font === null) {
      t.skip('本机未发现可用 TrueType 字体');
      return;
    }
    const result = writePdf(longChineseDoc(), { font, subsetFont: true });
    const stats = result.subset;
    assert.ok(stats !== null && stats !== undefined, 'subsets 必须存在');
    assert.ok(stats.glyphsKept > 0);
    assert.ok(stats.glyphsKept < stats.glyphsTotal, `kept ${stats.glyphsKept} 应小于 total ${stats.glyphsTotal}`);
    assert.ok(stats.glyphsKept < 1000, `中文报告的用字数不该上千，实际 ${stats.glyphsKept}`);
    assert.ok(stats.fontBytesAfter < stats.fontBytesBefore / 3, '字体程序至少要缩到 1/3 以下');
    assert.ok(stats.fontBytesAfter < 500_000, `子集字体程序应 < 500KB，实际 ${stats.fontBytesAfter}`);
    assert.ok(stats.fontBytesBefore > 10_000_000, '整份 CJK 字体程序应有十几 MB');
    assert.equal(result.fontPath, font.path);
  });

  test('子集 sfnt 结构合法：tag 升序 / 4 字节对齐 / checkSum / loca 与 maxp、head 一致', (t) => {
    if (font === null) {
      t.skip('本机未发现可用 TrueType 字体');
      return;
    }
    const result = writePdf(longChineseDoc(), { font, subsetFont: true });
    const sfnt = parseSubset(result.data);
    assertSubsetSfntStructure(sfnt);

    const stats = result.subset;
    assert.ok(stats !== null && stats !== undefined);
    assert.ok(sfnt.numGlyphs >= stats.glyphsKept, 'numGlyphs 至少要覆盖到保留的最大 gid');
    // 只保留需要的表
    const tags = sfnt.records.map((record) => record.tag);
    for (const dropped of ['GSUB', 'GPOS', 'GDEF', 'kern', 'gasp', 'hdmx', 'LTSH', 'VDMX']) {
      assert.ok(!tags.includes(dropped), `${dropped} 不应出现在子集里`);
    }
  });

  test('复合字形闭包（真实字体）：用到的 gid 是复合字形时，组件也被带进子集', (t) => {
    if (font === null) {
      t.skip('本机未发现可用 TrueType 字体');
      return;
    }
    // Latin-1 重音字母在多数 CJK 字体里是「基字母 + 重音」的复合字形
    const result = writePdf({ sections: [{ paragraphs: ['ÀÉÎÕÜ àéîõü ¼½¾ ÇÑ'] }] }, { font, subsetFont: true });
    const sfnt = parseSubset(result.data);
    assertSubsetSfntStructure(sfnt);
    const used = usedGlyphsFromPdf(result.data);
    const present = presentGlyphs(sfnt);

    const composites = [...used].filter((gid) => glyphIsComposite(sfnt, gid));
    if (composites.length === 0) {
      t.skip('该字体的重音字母不是复合字形，闭包由下面的合成字体用例覆盖');
      return;
    }

    let closureOnly = 0;
    for (const gid of composites) {
      for (const component of glyphComponents(sfnt, gid)) {
        assert.ok(present.has(component), `复合字形 ${gid} 的组件 ${component} 必须出现在子集里（否则缺笔画）`);
        if (!used.has(component)) closureOnly += 1;
      }
    }
    assert.ok(closureOnly > 0, '至少要有一个组件字形是「只被复合引用、没被直接用」的，才能证明递归闭包真的生效');
  });

  test('复合字形闭包（合成字体）：kept === 用到的 gid ∪ 递归组件闭包，含嵌套复合', () => {
    const fixture = writeFixtureFont('composite', buildCompositeFixture());

    // 文档只出现 'B'（gid 2）→ 必须带出组件 gid 1 与 gid 3
    const forB = writePdf({ sections: [{ paragraphs: ['B'] }] }, { font: fixture, subsetFont: true });
    const sfntB = parseSubset(forB.data);
    assertSubsetSfntStructure(sfntB);
    const usedB = usedGlyphsFromPdf(forB.data);
    const presentB = presentGlyphs(sfntB);
    assert.ok(usedB.has(2), `'B' 应映射到 gid 2，实际用到 ${[...usedB].join(',')}`);
    assert.deepEqual(
      [...presentB].sort((a, b) => a - b),
      [0, 1, 2, 3],
      '子集必须正好是 {0} ∪ {2} ∪ 组件闭包 {1,3}',
    );
    assert.ok(!usedB.has(1) && !usedB.has(3), 'gid 1/3 没有被直接使用，只能来自复合组件闭包');

    // 文档只出现 'D'（gid 4）→ D → 2 → 1,3 的两层嵌套闭包
    const forD = writePdf({ sections: [{ paragraphs: ['D'] }] }, { font: fixture, subsetFont: true });
    const sfntD = parseSubset(forD.data);
    assertSubsetSfntStructure(sfntD);
    const usedD = usedGlyphsFromPdf(forD.data);
    const presentD = presentGlyphs(sfntD);
    assert.ok(usedD.has(4));
    assert.deepEqual(
      [...presentD].sort((a, b) => a - b),
      [0, 1, 2, 3, 4],
      '嵌套复合字形 D → B → {1,3} 必须全部被带进子集',
    );
    assert.ok(!usedD.has(1) && !usedD.has(2) && !usedD.has(3), '嵌套的中间字形只能来自闭包');
  });

  test('subsetFont: false 与整份嵌入行为一致（回归）', (t) => {
    if (font === null) {
      t.skip('本机未发现可用 TrueType 字体');
      return;
    }
    const result = writePdf(chineseDoc(), { font, subsetFont: false });
    assert.equal(result.font, 'embedded');
    assert.equal(result.subset, null, '关闭子集化时 subset 必须是 null');
    assertPdfStructure(result.data);
    assert.ok(result.data.includes('/Type0'));
    assert.ok(result.data.includes('/Identity-H'));
    assert.ok(result.data.includes('/CIDFontType2'));
    assert.ok(result.data.includes('/FontFile2'));
    assert.ok(result.data.includes('/ToUnicode'));
    assert.ok(/<[0-9a-f]{4,}> Tj/.test(asText(result.data)));
    // 整份字体嵌入：解出来的程序长度 = 原字体程序长度
    const full = extractFontFile2(result.data);
    assert.ok(full.length > 10_000_000, `整份字体应该很大，实际 ${full.length}`);
  });

  test('子集路径同样字节确定', (t) => {
    if (font === null) {
      t.skip('本机未发现可用 TrueType 字体');
      return;
    }
    const first = writePdf(chineseDoc(), { font, subsetFont: true });
    const second = writePdf(chineseDoc(), { font, subsetFont: true });
    assert.equal(Buffer.compare(first.data, second.data), 0, '子集路径必须字节确定');
    assert.deepEqual(first.subset, second.subset);
  });

  test('损坏的字体：子集化失败安全回退整份嵌入，subset === null 且 PDF 合法', () => {
    const fixture = writeFixtureFont('broken', buildCompositeFixture(true));
    const result = writePdf({ title: 'Broken font', sections: [{ paragraphs: ['B'] }] }, { font: fixture });
    assert.equal(result.subset, null, '子集化失败必须如实返回 null');
    assert.equal(result.font, 'embedded');
    assertPdfStructure(result.data);
    assert.ok(result.data.includes('/FontFile2'), '回退后仍必须整份嵌入字体');

    // 对照：同一字体未损坏时是可以子集化的
    const healthy = writeFixtureFont('healthy', buildCompositeFixture());
    const ok = writePdf({ title: 'Healthy font', sections: [{ paragraphs: ['B'] }] }, { font: healthy });
    const healthyStats = ok.subset;
    assert.ok(healthyStats !== null && healthyStats !== undefined, '未损坏的同一字体必须能子集化');
    assert.ok(healthyStats.glyphsKept < healthyStats.glyphsTotal, '子集必须真的丢掉字形');
  });
});
