/**
 * E2E / UI 演示种子（仅本地演示用）
 *
 * 由 persistent-store.ts 在模块作用域触发（RF_E2E_DEMO=1 且非生产）：
 * 向内存提案库写入两个演示提案（一个 create、一个 modify），
 * 供 /enterprise/approvals 展示增/删/上下文 diff。
 *
 * 为什么挂在这里：dev 模式下 proxy/路由/instrumentation 各自持有独立
 * 模块实例，只有“每个模块图自我播种”才可靠。演示角色播种见
 * auth-guard.ts 模块作用域。幂等：同 id 提案已存在则跳过。
 */

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { demoStoreFileExists } from './proposal-store';
import type { CodingProposal } from './types';

interface DemoProposalStore {
  saveProposal: (proposal: CodingProposal, tenantId: string) => Promise<void>;
  getProposalById: (id: string, tenantId?: string) => Promise<CodingProposal | undefined>;
}

export const DEMO_USER_ID = 'demo-owner';
export const DEMO_TENANT_ID = 'tenant_demo';

const WIDGET_CONTENT = `// Demo widget — generated by the AI Coding Agent during E2E acceptance
export interface LoyaltyBannerProps {
  points: number;
  tier: 'silver' | 'gold' | 'platinum';
}

export function formatLoyaltyMessage(props: LoyaltyBannerProps): string {
  const next = props.tier === 'gold' ? 'platinum' : 'gold';
  return \`You have \${props.points} points — keep going to reach \${next} tier!\`;
}
`;

/**
 * modify 演示提案的目标必须是 git 已跟踪文件（untracked 文件会让
 * merge 因 "untracked working tree files would be overwritten" 失败——
 * 这是 apply 引擎正确的安全行为）。因此在播种时读取当前内容并追加一节。
 */
const MODIFY_TARGET = 'docs/Progress-Status.md';
const APPEND_SECTION = `
## Approval Pipeline Guarantee

Every change proposed by the AI Coding Agent must pass human review, the
automated test gate (unit tests + type check), and remains rollbackable via
\`git revert\`. See /enterprise/approvals for the review console.
`;

function buildModifiedDoc(): string {
  try {
    const current = readFileSync(path.join(process.cwd(), MODIFY_TARGET), 'utf8');
    if (current.includes('## Approval Pipeline Guarantee')) return current;
    // 同时替换“更新时间”行，让 diff 演示包含删除行（红）+ 新增行（绿）
    const touched = current.replace(
      /^> 更新时间：.*$/m,
      '> 更新时间：2026-09-04（AI Coding Agent 演示更新）'
    );
    return `${touched.replace(/\s*$/, '')}\n\n${APPEND_SECTION.trimStart()}`;
  } catch {
    return `# Progress Status\n\n${APPEND_SECTION.trimStart()}`;
  }
}

/** 幂等：后备文件已存在（含历史状态）则跳过；否则按 id 判重 */
export async function seedApprovalDemo(store: DemoProposalStore): Promise<void> {
  if (demoStoreFileExists()) return;
  if (await store.getProposalById('cprop_demo_widget', DEMO_TENANT_ID)) return;

  const now = new Date().toISOString();
  await store.saveProposal(
    {
      id: 'cprop_demo_widget',
      taskId: 'task_demo_widget',
      status: 'pending_review',
      title: 'Add loyalty banner widget',
      summary:
        'Creates a reusable loyalty banner helper under src/custom/demo/ so storefronts can render points/tier messaging without touching core code.',
      changes: [
        {
          filePath: 'src/custom/demo/loyalty-banner.ts',
          operation: 'create',
          proposedContent: WIDGET_CONTENT,
          rationale:
            'New file keeps demo logic isolated inside the tenant customization boundary; no core code is touched.',
        },
      ],
      riskLevel: 'safe',
      requiresHumanApproval: true,
      blockedPaths: [],
      generatedAt: now,
      model: 'claude-sonnet-4',
    },
    DEMO_TENANT_ID
  );

  await store.saveProposal(
    {
      id: 'cprop_demo_readme',
      taskId: 'task_demo_readme',
      status: 'pending_review',
      title: 'Document approval pipeline guarantee',
      summary:
        'Appends an "Approval Pipeline Guarantee" section to docs/Progress-Status.md documenting that agent changes require human approval, pass the test gate, and stay rollbackable.',
      changes: [
        {
          filePath: MODIFY_TARGET,
          operation: 'modify',
          proposedContent: buildModifiedDoc(),
          rationale:
            'Keeps progress docs in sync with the approval/rollback guarantee reviewers rely on.',
        },
      ],
      riskLevel: 'moderate',
      requiresHumanApproval: true,
      blockedPaths: [],
      generatedAt: now,
      model: 'claude-sonnet-4',
    },
    DEMO_TENANT_ID
  );

  console.log('[demo] approval demo seeded: 2 proposals for tenant', DEMO_TENANT_ID);
}
