/**
 * Phase 4c 探针：中文字体发现 + 真实中文 PDF 生成（只读/临时输出）。
 *
 * 回答两个问题：
 *   1. discoverPdfFont() 在本机找到什么
 *   2. 用该字体能否真正产出含中文的 PDF（不产出「豆腐块」）
 */
import { writeFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

import {
  discoverPdfFont,
  needsUnicodeFont,
  writePdf,
} from '../src/lib/artifacts/pdf-writer';

const font = discoverPdfFont();
console.log('FONT_PATH=' + (font ? font.path : 'null'));
console.log('FAMILY=' + (font ? font.familyName : 'null'));
console.log('GLYPHS=' + (font ? font.glyphCount : 'null'));
console.log('needsUnicodeFont_zh=' + needsUnicodeFont('中文测试'));
console.log('needsUnicodeFont_ascii=' + needsUnicodeFont('hello'));

if (!font) {
  console.log('[verdict] 未发现可用字体 —— 中文 PDF 会走 pdf_font_unavailable 降级');
  process.exit(2);
}

// 真正产出一个中文 PDF
const doc = {
  title: '经营分析报告',
  subtitle: '四川人家 · 2026 年 9 月',
  sections: [
    {
      heading: '一、本周概览',
      paragraphs: ['本周营收环比上升 12.4%，订单量 386 单。'],
      bullets: ['差评率下降至 2.1%', '库存告警 3 条'],
    },
  ],
};

const written = writePdf(doc as never, { font, watermark: 'Generated by RoveFrame AI COO' });
const dir = mkdtempSync(path.join(tmpdir(), 'rf-pdf-'));
const out = path.join(dir, 'report-zh.pdf');
writeFileSync(out, written.data);

const head = written.data.subarray(0, 8).toString('ascii');
console.log('written bytes ->', written.data.length);
console.log('pdf header ->', JSON.stringify(head));
console.log('requiresUnicodeFont flag ->', written.requiresUnicodeFont);
console.log('output ->', out);
console.log('[verdict] 中文 PDF 生成成功（字体已嵌入）');
