/**
 * Phase 6 — Deployment Engine
 *
 * 一句话部署：输入 { domain, environment, 服务器类型 }，生成完整部署产物包：
 *
 *   Dockerfile          — 多阶段构建（deps → build → runtime）
 *   docker-compose.yml  — app + 健康检查 + 自动重启
 *   nginx.conf          — 反向代理 + gzip + 静态缓存 +（可选）SSL
 *   deploy.sh           — 服务器端一键脚本：构建 → 迁移 → 启动 → SSL → 健康检查
 *   .env.template       — 环境变量清单
 *
 * 设计边界（务实，不过度设计）：
 *   - 本模块只生成产物与脚本，不直接 SSH 到用户服务器执行
 *   - SSL 使用 certbot --nginx 半自动（脚本内含命令，需人工确认邮箱）
 *   - 所有生成内容确定性输出（无随机、无时间戳），可测试、可 diff
 */

export interface DeploymentConfig {
  /** 域名，如 app.example.com；留空则跳过 SSL/域名配置（仅 IP 访问） */
  domain?: string;
  /** 运行端口（容器内部） */
  port: number;
  /** 环境：production | staging */
  environment: 'production' | 'staging';
  /** 镜像名 */
  imageName: string;
  /** 健康检查路径 */
  healthPath: string;
  /** certbot 邮箱（启用 SSL 时建议提供） */
  sslEmail?: string;
}

export interface DeploymentArtifact {
  /** 相对路径，如 'Dockerfile' */
  path: string;
  content: string;
  /** 是否需要可执行权限（deploy.sh） */
  executable?: boolean;
}

export interface DeploymentPlan {
  config: DeploymentConfig;
  artifacts: DeploymentArtifact[];
  /** 人类可读的执行步骤 */
  steps: string[];
}

export const DEFAULT_DEPLOYMENT_CONFIG: DeploymentConfig = {
  port: 5000,
  environment: 'production',
  imageName: 'roveframe-ai-business-os',
  healthPath: '/en',
};

// ---------------------------------------------------------------------------
// 校验
// ---------------------------------------------------------------------------

export function validateDeploymentConfig(
  input: Partial<DeploymentConfig>
): { valid: boolean; errors: string[]; config: DeploymentConfig } {
  const errors: string[] = [];
  const config: DeploymentConfig = { ...DEFAULT_DEPLOYMENT_CONFIG, ...input };

  if (config.domain !== undefined && config.domain !== '') {
    if (!/^(?=.{1,253}$)([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$/i.test(config.domain)) {
      errors.push(`invalid domain: ${config.domain}`);
    }
  }
  if (!Number.isInteger(config.port) || config.port < 1 || config.port > 65535) {
    errors.push(`invalid port: ${config.port}`);
  }
  if (config.environment !== 'production' && config.environment !== 'staging') {
    errors.push(`invalid environment: ${config.environment}`);
  }
  if (!/^[a-z0-9][a-z0-9._/-]{0,127}$/.test(config.imageName)) {
    errors.push(`invalid imageName: ${config.imageName}`);
  }
  if (!config.healthPath.startsWith('/')) {
    errors.push('healthPath must start with /');
  }
  if (config.sslEmail && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(config.sslEmail)) {
    errors.push(`invalid sslEmail: ${config.sslEmail}`);
  }

  return { valid: errors.length === 0, errors, config };
}

// ---------------------------------------------------------------------------
// 生成器
// ---------------------------------------------------------------------------

function dockerfile(): string {
  return `# syntax=docker/dockerfile:1
# RoveFrame AI Business OS — production image (generated by Deployment Engine)

FROM node:22-alpine AS deps
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

FROM node:22-alpine AS build
WORKDIR /app
RUN corepack enable
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN pnpm build

FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
RUN corepack enable && addgroup -S app && adduser -S app -G app
COPY --from=build /app/package.json /app/pnpm-lock.yaml ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/.next ./.next
COPY --from=build /app/dist ./dist
COPY --from=build /app/public ./public
COPY --from=build /app/messages ./messages
COPY --from=build /app/next.config.ts ./
USER app
EXPOSE 5000
CMD ["node", "dist/server.js"]
`;
}

function dockerCompose(c: DeploymentConfig): string {
  return `# Generated by Deployment Engine — ${c.environment}
services:
  app:
    image: ${c.imageName}:latest
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=${c.port}
    env_file:
      - .env
    ports:
      - "127.0.0.1:${c.port}:${c.port}"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://127.0.0.1:${c.port}${c.healthPath}"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
`;
}

function nginxConf(c: DeploymentConfig): string {
  const serverName = c.domain ? c.domain : '_';
  const sslBlock = c.domain
    ? `
    listen 443 ssl;
    # certbot 会填充以下两行（deploy.sh 步骤 4 自动执行）
    # ssl_certificate     /etc/letsencrypt/live/${c.domain}/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/${c.domain}/privkey.pem;
`
    : '';
  const listenLine = c.domain ? `listen 80;\n    ${sslBlock.trimStart()}` : 'listen 80;';

  return `# Generated by Deployment Engine — nginx reverse proxy
upstream roveframe_app {
    server 127.0.0.1:${c.port};
    keepalive 32;
}

server {
    ${listenLine}
    server_name ${serverName};

    gzip on;
    gzip_types text/plain text/css application/json application/javascript image/svg+xml;

    client_max_body_size 60m; # 允许商品视频上传（<=50MB）

    location /_next/static/ {
        proxy_pass http://roveframe_app;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location / {
        proxy_pass http://roveframe_app;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 120s; # SSE 流式响应
    }
}

# WebSocket/SSE upgrade map
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
`;
}

function envTemplate(): string {
  return `# RoveFrame runtime environment — fill in real values, NEVER commit this file
COZE_SUPABASE_URL=
COZE_SUPABASE_ANON_KEY=
COZE_SUPABASE_SERVICE_ROLE_KEY=
# AI provider keys are managed encrypted via Settings page; do not put them here
`;
}

function deploySh(c: DeploymentConfig): string {
  const sslStep = c.domain
    ? `
echo "[4/5] SSL via certbot"
if command -v certbot >/dev/null 2>&1; then
  certbot --nginx -d ${c.domain} --non-interactive --agree-tos ${c.sslEmail ? `-m ${c.sslEmail}` : '--register-unsafely-without-email'} || echo "certbot failed — run manually"
else
  echo "certbot not installed; install it and run: certbot --nginx -d ${c.domain}"
fi
`
    : `
echo "[4/5] SSL skipped (no domain configured)"
`;

  return `#!/usr/bin/env bash
# Generated by Deployment Engine — one-shot deploy script
# Usage: bash deploy.sh
set -Eeuo pipefail

echo "[1/5] Build image"
docker compose build

echo "[2/5] Database migrations"
echo "Open Supabase SQL Editor and apply: scripts/migrate.sql, scripts/migrate-business-tables.sql, scripts/migrate-production-hardening.sql"
echo "(idempotent; press Enter when done)"
read -r _

echo "[3/5] Start services"
docker compose up -d
${sslStep}
echo "[5/5] Health check"
for i in $(seq 1 30); do
  if curl -fsS "http://127.0.0.1:${c.port}${c.healthPath}" >/dev/null 2>&1; then
    echo "OK: service healthy"
    exit 0
  fi
  sleep 2
done
echo "FAIL: health check did not pass" >&2
exit 1
`;
}

// ---------------------------------------------------------------------------
// 入口
// ---------------------------------------------------------------------------

export function generateDeploymentPlan(input: Partial<DeploymentConfig>): DeploymentPlan {
  const { valid, errors, config } = validateDeploymentConfig(input);
  if (!valid) {
    throw new Error(`invalid deployment config: ${errors.join('; ')}`);
  }

  const artifacts: DeploymentArtifact[] = [
    { path: 'Dockerfile', content: dockerfile() },
    { path: 'docker-compose.yml', content: dockerCompose(config) },
    { path: 'deploy/nginx.conf', content: nginxConf(config) },
    { path: '.env.template', content: envTemplate() },
    { path: 'deploy.sh', content: deploySh(config), executable: true },
  ];

  const steps = [
    '将代码与生成产物上传至服务器（git clone 或 rsync）',
    '复制 .env.template 为 .env 并填入 Supabase 凭据',
    '安装 Docker 与 docker compose 插件',
    `将 nginx.conf 链接到 /etc/nginx/conf.d/roveframe.conf 并 nginx -s reload`,
    '执行 bash deploy.sh（构建 → 迁移 → 启动 → SSL → 健康检查）',
  ];

  return { config, artifacts, steps };
}
