/**
 * 零依赖文档 / 表格序列化器（artifact writers）。
 *
 * 用途：AI COO 的「产物导出」链路 —— 把结构化的表格（TableSpec）与文档（DocSpec）
 * 序列化成可直接下载 / 落盘的字节流（WrittenFile：data + mime + ext）。
 * 本模块**只依赖 Node.js 内置模块**（node:zlib + Buffer），不引入任何第三方依赖，
 * 因此可以在 API 路由、脚本、测试中被安全复用。
 *
 * 能力矩阵：
 * - writeTable   ：csv（UTF-8 BOM + RFC4180 转义）/ xlsx（真实 OOXML，ZIP 包）/ md / html / json
 * - writeDocument：docx（真实 OOXML，ZIP 包）/ md / txt / html / json
 * - 不支持的组合一律抛出 Error（例如 writeTable('docx') / writeDocument('csv')）。
 *
 * 实现要点：
 * - 私有 buildZip：最小 ZIP writer（deflateRaw，compression method 8），CRC-32 用自实现查表算法；
 *   写入 Local File Header + Central Directory + EOCD，文件名 UTF-8 且 general purpose flag = 0x0800；
 *   时间戳固定（1980-01-01 00:00），因此同样输入**输出字节完全确定**，可直接被单测严格断言。
 * - xlsx：inlineStr 内联字符串（不生成 sharedStrings.xml），数字写数值单元格，布尔写 t="b"，
 *   表头复用 styles.xml 里的加粗字体（s="1"）；工作表名清洗 `[]:*?/\`、截断 31 字符并去重。
 * - docx：标题 / 小节标题通过 w:pStyle 引用 styles.xml 中的 Heading1 / Heading2；
 *   列表用 ListParagraph 段落 + “• ” 文本前缀（**有意不引入 numbering.xml**，避免复杂依赖链）；
 *   表格是真实的 w:tbl（内联 tblBorders）；页脚（footer）写成独立的 word/footer1.xml 部件 + sectPr 引用。
 * - html：完整、自包含、内联 CSS、A4 友好（@page + 打印媒体查询），无任何外部资源，可直接浏览器打开并「打印成 PDF」。
 *
 * 有意为之的简化（不是 bug）：
 * - xlsx 只有一个加粗表头样式，不写主题 / 数字格式 / 列宽 / 冻结窗格；正文单元格全部为 inlineStr 或数值；
 * - docx 不支持富文本（粗体/斜体行内标记）、图片、目录；
 * - 表格宽度以 columns 定义为唯一口径：多出的行值被忽略，缺失的补空单元格（对全部格式一致）。
 */

import { deflateRawSync } from 'node:zlib';

/* -------------------------------------------------------------------------- */
/* 公共类型                                                                    */
/* -------------------------------------------------------------------------- */

export type ArtifactFormat = 'csv' | 'xlsx' | 'docx' | 'md' | 'txt' | 'json' | 'html';

export interface TableSpec {
  /** 工作表名（xlsx）/ 表标题（md/html） */
  name: string;
  columns: string[];
  rows: Array<Array<string | number | boolean | null>>;
}

export interface DocSection {
  heading?: string;
  paragraphs?: string[];
  bullets?: string[];
  table?: TableSpec;
}

export interface DocSpec {
  title?: string;
  subtitle?: string;
  sections: DocSection[];
  /** 页脚署名，如 "Generated by RoveFrame AI COO" */
  footer?: string;
}

export interface WrittenFile {
  data: Buffer;
  mime: string;
  ext: string;
}

type CellValue = string | number | boolean | null;

const TABLE_FORMATS: readonly ArtifactFormat[] = ['csv', 'xlsx', 'md', 'html', 'json'];
const DOCUMENT_FORMATS: readonly ArtifactFormat[] = ['docx', 'md', 'txt', 'html', 'json'];

const FORMAT_META: Record<ArtifactFormat, { mime: string; ext: string }> = {
  csv: { mime: 'text/csv; charset=utf-8', ext: 'csv' },
  xlsx: {
    mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    ext: 'xlsx',
  },
  docx: {
    mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    ext: 'docx',
  },
  md: { mime: 'text/markdown; charset=utf-8', ext: 'md' },
  txt: { mime: 'text/plain; charset=utf-8', ext: 'txt' },
  json: { mime: 'application/json; charset=utf-8', ext: 'json' },
  html: { mime: 'text/html; charset=utf-8', ext: 'html' },
};

function written(format: ArtifactFormat, data: Buffer): WrittenFile {
  const meta = FORMAT_META[format];
  return { data, mime: meta.mime, ext: meta.ext };
}

function unsupported(format: ArtifactFormat, api: string, allowed: readonly ArtifactFormat[]): never {
  throw new Error(
    `${api}: 不支持的格式 "${String(format)}"（支持：${allowed.join(' / ')}）`,
  );
}

/* -------------------------------------------------------------------------- */
/* 取值与转义                                                                  */
/* -------------------------------------------------------------------------- */

/** 单元格值 → 字符串（null / 非有限数字 → 空串）。 */
function cellText(value: CellValue): string {
  if (value === null) return '';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : '';
  return value;
}

/** 把多行文本压成单行（用于注释行 / 标题等不允许换行的位置）。 */
function oneLine(text: string): string {
  return text.replace(/[\r\n]+/g, ' ');
}

/**
 * 容错读取表结构：真实调用方（artifact store）传给这里的是模型输出经 `JSON.parse` 的
 * 结果，字段可能缺失或类型不对 —— 容器不是数组时按空处理，绝不抛 TypeError。
 */
function tableShape(sheet: TableSpec): { columns: string[]; rows: CellValue[][] } {
  const columns = Array.isArray(sheet.columns) ? sheet.columns : [];
  const rows = Array.isArray(sheet.rows)
    ? sheet.rows.map((row) => (Array.isArray(row) ? row : []))
    : [];
  return { columns, rows };
}

/** 丢弃 XML 1.0 不允许的字符（控制字符、孤立代理项、U+FFFE/U+FFFF）。 */
function stripInvalidXmlChars(input: string): string {
  let out = '';
  for (let i = 0; i < input.length; i += 1) {
    const code = input.charCodeAt(i);
    if (code >= 0xd800 && code <= 0xdbff) {
      const next = input.charCodeAt(i + 1);
      if (next >= 0xdc00 && next <= 0xdfff) {
        out += input[i] + input[i + 1];
        i += 1;
      }
      continue;
    }
    if (code >= 0xdc00 && code <= 0xdfff) continue;
    if (code === 0x9 || code === 0xa || code === 0xd) {
      out += input[i];
      continue;
    }
    if (code >= 0x20 && code !== 0xfffe && code !== 0xffff) out += input[i];
  }
  return out;
}

/** XML 文本 / 属性转义。 */
function escapeXml(input: string): string {
  return stripInvalidXmlChars(input)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/** HTML 文本 / 属性转义。 */
function escapeHtml(input: string): string {
  return input
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** HTML 文本单元格：先转义，再把换行变成 <br />。 */
function htmlCell(input: string): string {
  return escapeHtml(input).replace(/\r\n|\r|\n/g, '<br />');
}

/* -------------------------------------------------------------------------- */
/* 最小 ZIP writer（导出 crc32 / buildZip 仅为单测复用）                        */
/* -------------------------------------------------------------------------- */

interface ZipEntry {
  name: string;
  data: Buffer;
}

const ZIP_LOCAL_SIG = 0x04034b50;
const ZIP_CENTRAL_SIG = 0x02014b50;
const ZIP_EOCD_SIG = 0x06054b50;
const ZIP_VERSION = 20;
/** general purpose bit flag：文件名为 UTF-8 */
const ZIP_FLAG_UTF8 = 0x0800;
/** compression method：deflate */
const ZIP_METHOD_DEFLATE = 8;
/** 固定时间戳 1980-01-01 00:00:00，保证输出确定性 */
const ZIP_DOS_TIME = 0;
const ZIP_DOS_DATE = 0x0021;

const CRC32_TABLE: Uint32Array = (() => {
  const table = new Uint32Array(256);
  for (let i = 0; i < 256; i += 1) {
    let c = i;
    for (let k = 0; k < 8; k += 1) {
      c = (c & 1) !== 0 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    }
    table[i] = c >>> 0;
  }
  return table;
})();

/** CRC-32（IEEE 802.3，查表法）。 */
export function crc32(buf: Buffer): number {
  let crc = 0xffffffff;
  for (let i = 0; i < buf.length; i += 1) {
    crc = CRC32_TABLE[(crc ^ buf[i]) & 0xff] ^ (crc >>> 8);
  }
  return (crc ^ 0xffffffff) >>> 0;
}

/**
 * 打包成 ZIP：Local File Header + 文件数据 + Central Directory + EOCD。
 * 所有 entry 使用 deflateRaw，文件名统一 `/` 分隔并以 UTF-8 写入。
 */
export function buildZip(entries: ZipEntry[]): Buffer {
  const localParts: Buffer[] = [];
  const centralParts: Buffer[] = [];
  let offset = 0;

  for (const entry of entries) {
    const nameBuf = Buffer.from(entry.name, 'utf8');
    const raw = entry.data;
    const compressed = deflateRawSync(raw);
    const checksum = crc32(raw);

    const local = Buffer.alloc(30);
    local.writeUInt32LE(ZIP_LOCAL_SIG, 0);
    local.writeUInt16LE(ZIP_VERSION, 4);
    local.writeUInt16LE(ZIP_FLAG_UTF8, 6);
    local.writeUInt16LE(ZIP_METHOD_DEFLATE, 8);
    local.writeUInt16LE(ZIP_DOS_TIME, 10);
    local.writeUInt16LE(ZIP_DOS_DATE, 12);
    local.writeUInt32LE(checksum, 14);
    local.writeUInt32LE(compressed.length, 18);
    local.writeUInt32LE(raw.length, 22);
    local.writeUInt16LE(nameBuf.length, 26);
    local.writeUInt16LE(0, 28);
    localParts.push(local, nameBuf, compressed);

    const central = Buffer.alloc(46);
    central.writeUInt32LE(ZIP_CENTRAL_SIG, 0);
    central.writeUInt16LE(ZIP_VERSION, 4);
    central.writeUInt16LE(ZIP_VERSION, 6);
    central.writeUInt16LE(ZIP_FLAG_UTF8, 8);
    central.writeUInt16LE(ZIP_METHOD_DEFLATE, 10);
    central.writeUInt16LE(ZIP_DOS_TIME, 12);
    central.writeUInt16LE(ZIP_DOS_DATE, 14);
    central.writeUInt32LE(checksum, 16);
    central.writeUInt32LE(compressed.length, 20);
    central.writeUInt32LE(raw.length, 24);
    central.writeUInt16LE(nameBuf.length, 28);
    central.writeUInt16LE(0, 30);
    central.writeUInt16LE(0, 32);
    central.writeUInt16LE(0, 34);
    central.writeUInt16LE(0, 36);
    central.writeUInt32LE(0, 38);
    central.writeUInt32LE(offset, 42);
    centralParts.push(central, nameBuf);

    offset += local.length + nameBuf.length + compressed.length;
  }

  const centralBuf = Buffer.concat(centralParts);
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(ZIP_EOCD_SIG, 0);
  eocd.writeUInt16LE(0, 4);
  eocd.writeUInt16LE(0, 6);
  eocd.writeUInt16LE(entries.length, 8);
  eocd.writeUInt16LE(entries.length, 10);
  eocd.writeUInt32LE(centralBuf.length, 12);
  eocd.writeUInt32LE(offset, 16);
  eocd.writeUInt16LE(0, 20);

  return Buffer.concat([...localParts, centralBuf, eocd]);
}

/* -------------------------------------------------------------------------- */
/* CSV                                                                         */
/* -------------------------------------------------------------------------- */

/** RFC4180 字段转义：含逗号 / 双引号 / 换行的字段用双引号包裹，内部 `"` → `""`。 */
function csvField(value: string): string {
  return /[",\r\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value;
}

function csvRow(values: string[]): string {
  return values.map(csvField).join(',');
}

/**
 * CSV 文本（不含 BOM，调用方负责加 `\uFEFF`）。
 * 行分隔符用 RFC4180 规定的 CRLF；多表时用空行分隔，并在每张表前加 `# <name>` 注释行。
 */
function csvText(sheets: TableSpec[], title?: string): string {
  const lines: string[] = [];
  const trimmedTitle = title === undefined ? '' : oneLine(title).trim();
  if (trimmedTitle !== '') lines.push(`# ${trimmedTitle}`);

  const multi = sheets.length > 1;
  sheets.forEach((sheet, index) => {
    const { columns, rows } = tableShape(sheet);
    if (index > 0) lines.push('');
    if (multi) lines.push(`# ${oneLine(sheet.name)}`);
    lines.push(csvRow(columns));
    for (const row of rows) {
      lines.push(csvRow(columns.map((_, i) => cellText(row[i] ?? null))));
    }
  });

  return `${lines.join('\r\n')}\r\n`;
}

/* -------------------------------------------------------------------------- */
/* Markdown                                                                    */
/* -------------------------------------------------------------------------- */

/** markdown 单元格：转义 `|`，换行折叠为 `<br>`。 */
function mdCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\r\n|\r|\n/g, '<br>');
}

function mdTable(sheet: TableSpec): string {
  const { columns, rows } = tableShape(sheet);
  const lines: string[] = [];
  lines.push(`| ${columns.map(mdCell).join(' | ')} |`);
  lines.push(`| ${columns.map(() => '---').join(' | ')} |`);
  for (const row of rows) {
    const cells = columns.map((_, i) => mdCell(cellText(row[i] ?? null)));
    lines.push(`| ${cells.join(' | ')} |`);
  }
  return lines.join('\n');
}

function markdownTables(sheets: TableSpec[], title?: string): string {
  const blocks: string[] = [];
  const trimmedTitle = title === undefined ? '' : title.trim();
  if (trimmedTitle !== '') blocks.push(`# ${mdCell(trimmedTitle)}`);
  for (const sheet of sheets) {
    const parts: string[] = [];
    const name = sheet.name.trim();
    if (name !== '') parts.push(`## ${mdCell(name)}`);
    parts.push(mdTable(sheet));
    blocks.push(parts.join('\n\n'));
  }
  return blocks.length === 0 ? '' : `${blocks.join('\n\n')}\n`;
}

function markdownDocument(doc: DocSpec): string {
  const blocks: string[] = [];
  const title = (doc.title ?? '').trim();
  const subtitle = (doc.subtitle ?? '').trim();
  if (title !== '') blocks.push(`# ${mdCell(title)}`);
  if (subtitle !== '') blocks.push(`*${mdCell(subtitle)}*`);

  for (const section of doc.sections ?? []) {
    const parts: string[] = [];
    const heading = (section.heading ?? '').trim();
    if (heading !== '') parts.push(`## ${mdCell(heading)}`);
    for (const paragraph of section.paragraphs ?? []) parts.push(mdCell(paragraph));
    const bullets = section.bullets ?? [];
    if (bullets.length > 0) parts.push(bullets.map((b) => `- ${mdCell(b)}`).join('\n'));
    if (section.table !== undefined) {
      const block: string[] = [];
      const tableName = section.table.name.trim();
      if (tableName !== '') block.push(`**${mdCell(tableName)}**`);
      block.push(mdTable(section.table));
      parts.push(block.join('\n\n'));
    }
    if (parts.length > 0) blocks.push(parts.join('\n\n'));
  }

  const footer = (doc.footer ?? '').trim();
  if (footer !== '') blocks.push(`---\n\n${mdCell(footer)}`);

  return blocks.length === 0 ? '' : `${blocks.join('\n\n')}\n`;
}

/* -------------------------------------------------------------------------- */
/* 纯文本（txt）                                                               */
/* -------------------------------------------------------------------------- */

function txtTable(sheet: TableSpec): string {
  const { columns, rows } = tableShape(sheet);
  const header = columns.map(cellText);
  const body = rows.map((row) => columns.map((_, i) => cellText(row[i] ?? null)));
  const separator = columns
    .map((column) => '-'.repeat(Math.max(3, column.length)))
    .join('-+-');
  const lines = [header.join(' | '), separator, ...body.map((cells) => cells.join(' | '))];
  return lines.join('\n');
}

function textDocument(doc: DocSpec): string {
  const blocks: string[] = [];
  const title = (doc.title ?? '').trim();
  const subtitle = (doc.subtitle ?? '').trim();
  if (title !== '') {
    blocks.push(`${title}\n${'='.repeat(Math.max(1, title.length))}`);
  }
  if (subtitle !== '') blocks.push(subtitle);

  for (const section of doc.sections ?? []) {
    const parts: string[] = [];
    const heading = (section.heading ?? '').trim();
    if (heading !== '') parts.push(`${heading}\n${'-'.repeat(Math.max(1, heading.length))}`);
    for (const paragraph of section.paragraphs ?? []) parts.push(paragraph);
    const bullets = section.bullets ?? [];
    if (bullets.length > 0) parts.push(bullets.map((b) => `• ${b}`).join('\n'));
    if (section.table !== undefined) {
      const block: string[] = [];
      const tableName = section.table.name.trim();
      if (tableName !== '') block.push(`[${tableName}]`);
      block.push(txtTable(section.table));
      parts.push(block.join('\n'));
    }
    if (parts.length > 0) blocks.push(parts.join('\n\n'));
  }

  const footer = (doc.footer ?? '').trim();
  if (footer !== '') blocks.push(`${'-'.repeat(40)}\n${footer}`);

  return blocks.length === 0 ? '' : `${blocks.join('\n\n')}\n`;
}

/* -------------------------------------------------------------------------- */
/* HTML（自包含 + A4 打印友好）                                                */
/* -------------------------------------------------------------------------- */

const HTML_STYLE = [
  '@page { size: A4; margin: 16mm 14mm; }',
  '*, *::before, *::after { box-sizing: border-box; }',
  'html { -webkit-text-size-adjust: 100%; }',
  'body {',
  '  margin: 0;',
  '  background: #f4f5f7;',
  '  color: #1f2933;',
  '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", "PingFang SC", "Microsoft YaHei", sans-serif;',
  '  font-size: 12pt;',
  '  line-height: 1.6;',
  '}',
  '.page {',
  '  max-width: 190mm;',
  '  margin: 0 auto;',
  '  padding: 16mm 14mm;',
  '  background: #ffffff;',
  '  box-shadow: 0 2px 10px rgba(15, 23, 42, 0.08);',
  '}',
  'h1, h2, h3 { line-height: 1.3; margin: 0 0 0.5em; page-break-after: avoid; break-after: avoid; }',
  'h1 { font-size: 20pt; }',
  'h2 { font-size: 14pt; margin-top: 1.4em; }',
  'h3 { font-size: 12pt; margin-top: 1.2em; }',
  'p { margin: 0 0 0.8em; }',
  '.doc-subtitle { color: #52606d; font-size: 11pt; margin-top: -0.2em; }',
  'ul { margin: 0 0 0.9em; padding-left: 1.3em; }',
  'li { margin: 0.15em 0; }',
  '.sheet { margin-top: 1.2em; page-break-inside: auto; }',
  'table { width: 100%; border-collapse: collapse; margin: 0.4em 0 1em; font-size: 10pt; }',
  'th, td { border: 1px solid #cbd2d9; padding: 6px 8px; text-align: left; vertical-align: top; word-break: break-word; overflow-wrap: anywhere; }',
  'thead th { background: #eef1f4; font-weight: 600; }',
  'tbody tr:nth-child(even) { background: #fafbfc; }',
  'tr { page-break-inside: avoid; break-inside: avoid; }',
  'thead { display: table-header-group; }',
  '.doc-footer { margin-top: 2em; padding-top: 0.8em; border-top: 1px solid #d9dee3; color: #7b8794; font-size: 9.5pt; }',
  '.empty { color: #7b8794; font-style: italic; }',
  '@media print {',
  '  body { background: #ffffff; font-size: 11pt; }',
  '  .page { max-width: none; margin: 0; padding: 0; box-shadow: none; }',
  '  table { font-size: 9.5pt; }',
  '  th, td { padding: 4px 6px; }',
  '}',
].join('\n');

function htmlShell(options: { title: string; bodyBlocks: string[]; footer?: string }): string {
  const footer = (options.footer ?? '').trim();
  const body = [...options.bodyBlocks];
  if (footer !== '') body.push(`<footer class="doc-footer">${escapeHtml(footer)}</footer>`);
  return [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8" />',
    '<meta name="viewport" content="width=device-width, initial-scale=1" />',
    `<title>${escapeHtml(options.title)}</title>`,
    '<style>',
    HTML_STYLE,
    '</style>',
    '</head>',
    '<body>',
    '<main class="page">',
    ...body,
    '</main>',
    '</body>',
    '</html>',
    '',
  ].join('\n');
}

function htmlTable(sheet: TableSpec, headingLevel: 2 | 3): string {
  const { columns, rows } = tableShape(sheet);
  const head = `<thead><tr>${columns
    .map((column) => `<th scope="col">${htmlCell(column)}</th>`)
    .join('')}</tr></thead>`;
  const bodyRows = rows
    .map(
      (row) =>
        `<tr>${columns
          .map((_, i) => `<td>${htmlCell(cellText(row[i] ?? null))}</td>`)
          .join('')}</tr>`,
    )
    .join('');
  const name = sheet.name.trim();
  const caption = name === '' ? '' : `<h${headingLevel}>${escapeHtml(name)}</h${headingLevel}>`;
  const table = `<table>${head}<tbody>${bodyRows}</tbody></table>`;
  return `<section class="sheet">${caption}${table}</section>`;
}

function htmlTables(sheets: TableSpec[], title?: string): string {
  const trimmedTitle = (title ?? '').trim();
  const blocks: string[] = [];
  if (trimmedTitle !== '') blocks.push(`<h1>${escapeHtml(trimmedTitle)}</h1>`);
  if (sheets.length === 0) blocks.push('<p class="empty">No data.</p>');
  for (const sheet of sheets) blocks.push(htmlTable(sheet, 2));
  const fallbackTitle = trimmedTitle !== '' ? trimmedTitle : (sheets[0]?.name ?? 'Table export');
  return htmlShell({ title: fallbackTitle, bodyBlocks: blocks });
}

function htmlDocument(doc: DocSpec): string {
  const blocks: string[] = [];
  const title = (doc.title ?? '').trim();
  const subtitle = (doc.subtitle ?? '').trim();
  if (title !== '') blocks.push(`<h1>${escapeHtml(title)}</h1>`);
  if (subtitle !== '') blocks.push(`<p class="doc-subtitle">${escapeHtml(subtitle)}</p>`);

  for (const section of doc.sections ?? []) {
    const heading = (section.heading ?? '').trim();
    if (heading !== '') blocks.push(`<h2>${escapeHtml(heading)}</h2>`);
    for (const paragraph of section.paragraphs ?? []) {
      blocks.push(`<p>${htmlCell(paragraph)}</p>`);
    }
    const bullets = section.bullets ?? [];
    if (bullets.length > 0) {
      blocks.push(`<ul>${bullets.map((b) => `<li>${htmlCell(b)}</li>`).join('')}</ul>`);
    }
    if (section.table !== undefined) blocks.push(htmlTable(section.table, 3));
  }

  if (blocks.length === 0) blocks.push('<p class="empty">Empty document.</p>');
  const shellTitle = title !== '' ? title : 'Document';
  return htmlShell({ title: shellTitle, bodyBlocks: blocks, footer: doc.footer });
}

/* -------------------------------------------------------------------------- */
/* XLSX（真实 OOXML）                                                          */
/* -------------------------------------------------------------------------- */

const XML_DECL = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>';
const NS_SPREADSHEET =
  'xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"';
const NS_RELATIONSHIPS = 'xmlns="http://schemas.openxmlformats.org/package/2006/relationships"';
const NS_CONTENT_TYPES = 'xmlns="http://schemas.openxmlformats.org/package/2006/content-types"';
const NS_WORDPROCESSING =
  'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"';
/** OOXML officeDocument 关系命名空间（xlsx 的 r: 前缀与 .rels 中的 Type 前缀）。 */
const REL_NS = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships';
const NS_DOC_RELATIONSHIPS = `xmlns:r="${REL_NS}"`;

/** 0 → A、25 → Z、26 → AA。 */
function columnName(index: number): string {
  let n = index + 1;
  let out = '';
  while (n > 0) {
    const rem = (n - 1) % 26;
    out = String.fromCharCode(65 + rem) + out;
    n = Math.floor((n - 1) / 26);
  }
  return out;
}

/** Excel 工作表名不允许出现的字符：`[` `]` `:` `*` `?` `/` `\`。 */
const SHEET_NAME_INVALID_CHARS = /[[\]:*?/\\]/g;

/** 工作表名清洗：去掉 `[]:*?/\`，截断 31 字符，空名回落 SheetN，重名追加 ` (n)`。 */
function sanitizeSheetNames(sheets: TableSpec[]): string[] {
  const used = new Set<string>();
  return sheets.map((sheet, index) => {
    const raw = String(sheet.name ?? '').replace(SHEET_NAME_INVALID_CHARS, '').trim();
    const base = raw.length > 31 ? raw.slice(0, 31) : raw;
    const seed = base.length > 0 ? base : `Sheet${index + 1}`;
    let name = seed;
    let counter = 2;
    while (used.has(name.toLowerCase())) {
      const suffix = ` (${counter})`;
      name = `${seed.slice(0, Math.max(1, 31 - suffix.length))}${suffix}`;
      counter += 1;
    }
    used.add(name.toLowerCase());
    return name;
  });
}

function xlsxCell(ref: string, value: CellValue, styleIndex: number): string {
  const style = styleIndex > 0 ? ` s="${styleIndex}"` : '';
  if (value === null || value === '') return `<c r="${ref}"${style}/>`;
  if (typeof value === 'number') {
    return Number.isFinite(value)
      ? `<c r="${ref}"${style}><v>${value}</v></c>`
      : `<c r="${ref}" t="inlineStr"${style}><is><t xml:space="preserve">${escapeXml(String(value))}</t></is></c>`;
  }
  if (typeof value === 'boolean') {
    return `<c r="${ref}" t="b"${style}><v>${value ? 1 : 0}</v></c>`;
  }
  return `<c r="${ref}" t="inlineStr"${style}><is><t xml:space="preserve">${escapeXml(value)}</t></is></c>`;
}

function xlsxSheetXml(sheet: TableSpec): string {
  const { columns, rows } = tableShape(sheet);
  const colCount = columns.length;
  const out: string[] = [XML_DECL];
  out.push(`<worksheet ${NS_SPREADSHEET}>`);
  const lastRow = Math.max(1, rows.length + (colCount > 0 ? 1 : 0));
  out.push(`<dimension ref="A1:${columnName(Math.max(0, colCount - 1))}${lastRow}"/>`);
  out.push('<sheetViews><sheetView workbookViewId="0"/></sheetViews>');
  out.push('<sheetFormatPr defaultRowHeight="15"/>');
  out.push('<sheetData>');
  if (colCount > 0) {
    const header = columns.map((column, i) => xlsxCell(`${columnName(i)}1`, column, 1)).join('');
    out.push(`<row r="1">${header}</row>`);
  }
  rows.forEach((row, index) => {
    const rowNumber = index + (colCount > 0 ? 2 : 1);
    const cells = columns
      .map((_, i) => xlsxCell(`${columnName(i)}${rowNumber}`, row[i] ?? null, 0))
      .join('');
    out.push(`<row r="${rowNumber}">${cells}</row>`);
  });
  out.push('</sheetData>');
  out.push('</worksheet>');
  return out.join('');
}

const XLSX_STYLES = [
  XML_DECL,
  `<styleSheet ${NS_SPREADSHEET}>`,
  '<fonts count="2">',
  '<font><sz val="11"/><color theme="1"/><name val="Calibri"/><family val="2"/><scheme val="minor"/></font>',
  '<font><b/><sz val="11"/><color theme="1"/><name val="Calibri"/><family val="2"/><scheme val="minor"/></font>',
  '</fonts>',
  '<fills count="2">',
  '<fill><patternFill patternType="none"/></fill>',
  '<fill><patternFill patternType="gray125"/></fill>',
  '</fills>',
  '<borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders>',
  '<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>',
  '<cellXfs count="2">',
  '<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>',
  '<xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/>',
  '</cellXfs>',
  '<cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles>',
  '</styleSheet>',
].join('');

function xlsxWorkbook(sheets: TableSpec[]): WrittenFile {
  if (sheets.length === 0) {
    throw new Error('writeTable: xlsx 至少需要一张工作表（sheets 不能为空）');
  }
  const names = sanitizeSheetNames(sheets);
  const entries: ZipEntry[] = [];

  const contentTypes = [
    XML_DECL,
    `<Types ${NS_CONTENT_TYPES}>`,
    '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>',
    '<Default Extension="xml" ContentType="application/xml"/>',
    '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>',
    '<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>',
    ...sheets.map(
      (_, i) =>
        `<Override PartName="/xl/worksheets/sheet${i + 1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`,
    ),
    '</Types>',
  ].join('');
  entries.push({ name: '[Content_Types].xml', data: Buffer.from(contentTypes, 'utf8') });

  const rootRels = [
    XML_DECL,
    `<Relationships ${NS_RELATIONSHIPS}>`,
    `<Relationship Id="rId1" Type="${REL_NS}/officeDocument" Target="xl/workbook.xml"/>`,
    '</Relationships>',
  ].join('');
  entries.push({ name: '_rels/.rels', data: Buffer.from(rootRels, 'utf8') });

  const workbook = [
    XML_DECL,
    `<workbook ${NS_SPREADSHEET} ${NS_DOC_RELATIONSHIPS}>`,
    '<bookViews><workbookView xWindow="0" yWindow="0" windowWidth="20000" windowHeight="12000"/></bookViews>',
    '<sheets>',
    ...names.map(
      (name, i) => `<sheet name="${escapeXml(name)}" sheetId="${i + 1}" r:id="rId${i + 1}"/>`,
    ),
    '</sheets>',
    '</workbook>',
  ].join('');
  entries.push({ name: 'xl/workbook.xml', data: Buffer.from(workbook, 'utf8') });

  const workbookRels = [
    XML_DECL,
    `<Relationships ${NS_RELATIONSHIPS}>`,
    ...sheets.map(
      (_, i) =>
        `<Relationship Id="rId${i + 1}" Type="${REL_NS}/worksheet" Target="worksheets/sheet${i + 1}.xml"/>`,
    ),
    `<Relationship Id="rId${sheets.length + 1}" Type="${REL_NS}/styles" Target="styles.xml"/>`,
    '</Relationships>',
  ].join('');
  entries.push({ name: 'xl/_rels/workbook.xml.rels', data: Buffer.from(workbookRels, 'utf8') });

  sheets.forEach((sheet, i) => {
    entries.push({
      name: `xl/worksheets/sheet${i + 1}.xml`,
      data: Buffer.from(xlsxSheetXml(sheet), 'utf8'),
    });
  });

  entries.push({ name: 'xl/styles.xml', data: Buffer.from(XLSX_STYLES, 'utf8') });

  return written('xlsx', buildZip(entries));
}

/* -------------------------------------------------------------------------- */
/* DOCX（真实 OOXML）                                                          */
/* -------------------------------------------------------------------------- */

const DOCX_STYLES = [
  XML_DECL,
  `<w:styles ${NS_WORDPROCESSING}>`,
  '<w:docDefaults>',
  '<w:rPrDefault><w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri" w:eastAsia="SimSun" w:cs="Calibri"/>',
  '<w:sz w:val="22"/><w:szCs w:val="22"/></w:rPr></w:rPrDefault>',
  '<w:pPrDefault><w:pPr><w:spacing w:after="160" w:line="276" w:lineRule="auto"/></w:pPr></w:pPrDefault>',
  '</w:docDefaults>',
  '<w:style w:type="paragraph" w:default="1" w:styleId="Normal">',
  '<w:name w:val="Normal"/><w:qFormat/>',
  '</w:style>',
  '<w:style w:type="paragraph" w:styleId="Heading1">',
  '<w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:next w:val="Normal"/><w:qFormat/>',
  '<w:pPr><w:keepNext/><w:spacing w:before="240" w:after="120"/><w:outlineLvl w:val="0"/></w:pPr>',
  '<w:rPr><w:b/><w:sz w:val="36"/><w:szCs w:val="36"/></w:rPr>',
  '</w:style>',
  '<w:style w:type="paragraph" w:styleId="Heading2">',
  '<w:name w:val="heading 2"/><w:basedOn w:val="Normal"/><w:next w:val="Normal"/><w:qFormat/>',
  '<w:pPr><w:keepNext/><w:spacing w:before="200" w:after="100"/><w:outlineLvl w:val="1"/></w:pPr>',
  '<w:rPr><w:b/><w:sz w:val="28"/><w:szCs w:val="28"/></w:rPr>',
  '</w:style>',
  '<w:style w:type="paragraph" w:styleId="Subtitle">',
  '<w:name w:val="Subtitle"/><w:basedOn w:val="Normal"/><w:qFormat/>',
  '<w:rPr><w:i/><w:color w:val="52606D"/><w:sz w:val="22"/></w:rPr>',
  '</w:style>',
  '<w:style w:type="paragraph" w:styleId="ListParagraph">',
  '<w:name w:val="List Paragraph"/><w:basedOn w:val="Normal"/><w:qFormat/>',
  '<w:pPr><w:ind w:left="720"/><w:contextualSpacing/></w:pPr>',
  '</w:style>',
  '</w:styles>',
].join('');

function docxRun(text: string, bold = false): string {
  if (text === '') return '';
  const rPr = bold ? '<w:rPr><w:b/></w:rPr>' : '';
  return `<w:r>${rPr}<w:t xml:space="preserve">${escapeXml(text)}</w:t></w:r>`;
}

function docxParagraph(text: string, styleId?: string): string {
  const run = docxRun(text);
  if (run === '') return '<w:p/>';
  const pPr = styleId === undefined ? '' : `<w:pPr><w:pStyle w:val="${styleId}"/></w:pPr>`;
  return `<w:p>${pPr}${run}</w:p>`;
}

function docxTableRow(cells: string[], header: boolean): string {
  const trPr = header ? '<w:trPr><w:tblHeader/></w:trPr>' : '';
  const tcs = cells
    .map((text) => {
      const run = docxRun(text, header);
      const paragraph = run === '' ? '<w:p/>' : `<w:p>${run}</w:p>`;
      return `<w:tc><w:tcPr><w:tcW w:w="0" w:type="auto"/></w:tcPr>${paragraph}</w:tc>`;
    })
    .join('');
  return `<w:tr>${trPr}${tcs}</w:tr>`;
}

function docxTable(sheet: TableSpec): string {
  const { columns, rows: bodyRows } = tableShape(sheet);
  const borders =
    '<w:tblBorders>' +
    ['top', 'left', 'bottom', 'right', 'insideH', 'insideV']
      .map((side) => `<w:${side} w:val="single" w:sz="4" w:space="0" w:color="CBD2D9"/>`)
      .join('') +
    '</w:tblBorders>';
  const grid = columns.map(() => '<w:gridCol w:w="2400"/>').join('');
  const rows: string[] = [];
  if (columns.length > 0) rows.push(docxTableRow(columns.map((c) => c), true));
  for (const row of bodyRows) {
    rows.push(docxTableRow(columns.map((_, i) => cellText(row[i] ?? null)), false));
  }
  return (
    '<w:tbl>' +
    `<w:tblPr><w:tblW w:w="0" w:type="auto"/>${borders}<w:tblLayout w:type="autofit"/></w:tblPr>` +
    `<w:tblGrid>${grid}</w:tblGrid>` +
    rows.join('') +
    '</w:tbl>' +
    '<w:p/>'
  );
}

function docxFooterXml(footer: string): string {
  return [
    XML_DECL,
    `<w:ftr ${NS_WORDPROCESSING}>`,
    '<w:p><w:pPr><w:pStyle w:val="Subtitle"/><w:jc w:val="center"/></w:pPr>',
    `<w:r><w:rPr><w:i/><w:color w:val="7B8794"/><w:sz w:val="18"/></w:rPr><w:t xml:space="preserve">${escapeXml(footer)}</w:t></w:r>`,
    '</w:p>',
    '</w:ftr>',
  ].join('');
}

function docxDocumentBody(doc: DocSpec): string {
  const body: string[] = [];
  const title = (doc.title ?? '').trim();
  const subtitle = (doc.subtitle ?? '').trim();
  if (title !== '') body.push(docxParagraph(title, 'Heading1'));
  if (subtitle !== '') body.push(docxParagraph(subtitle, 'Subtitle'));

  for (const section of doc.sections ?? []) {
    const heading = (section.heading ?? '').trim();
    if (heading !== '') body.push(docxParagraph(heading, 'Heading2'));
    for (const paragraph of section.paragraphs ?? []) body.push(docxParagraph(paragraph));
    for (const bullet of section.bullets ?? []) {
      body.push(docxParagraph(`• ${bullet}`, 'ListParagraph'));
    }
    if (section.table !== undefined) body.push(docxTable(section.table));
  }

  if (body.length === 0) body.push('<w:p/>');
  return body.join('');
}

function docxDocument(doc: DocSpec): WrittenFile {
  const footer = (doc.footer ?? '').trim();
  const hasFooter = footer !== '';
  const entries: ZipEntry[] = [];

  const contentTypes = [
    XML_DECL,
    `<Types ${NS_CONTENT_TYPES}>`,
    '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>',
    '<Default Extension="xml" ContentType="application/xml"/>',
    '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>',
    '<Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>',
    ...(hasFooter
      ? [
          '<Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/>',
        ]
      : []),
    '</Types>',
  ].join('');
  entries.push({ name: '[Content_Types].xml', data: Buffer.from(contentTypes, 'utf8') });

  const rootRels = [
    XML_DECL,
    `<Relationships ${NS_RELATIONSHIPS}>`,
    '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>',
    '</Relationships>',
  ].join('');
  entries.push({ name: '_rels/.rels', data: Buffer.from(rootRels, 'utf8') });

  const documentRels = [
    XML_DECL,
    `<Relationships ${NS_RELATIONSHIPS}>`,
    '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>',
    ...(hasFooter
      ? [
          '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/>',
        ]
      : []),
    '</Relationships>',
  ].join('');
  entries.push({
    name: 'word/_rels/document.xml.rels',
    data: Buffer.from(documentRels, 'utf8'),
  });

  const sectPr =
    '<w:sectPr>' +
    (hasFooter ? '<w:footerReference w:type="default" r:id="rId2"/>' : '') +
    '<w:pgSz w:w="11906" w:h="16838"/>' +
    '<w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="708" w:footer="708" w:gutter="0"/>' +
    '</w:sectPr>';

  const document = [
    XML_DECL,
    `<w:document ${NS_WORDPROCESSING} ${NS_DOC_RELATIONSHIPS}>`,
    '<w:body>',
    docxDocumentBody(doc),
    sectPr,
    '</w:body>',
    '</w:document>',
  ].join('');
  entries.push({ name: 'word/document.xml', data: Buffer.from(document, 'utf8') });

  entries.push({ name: 'word/styles.xml', data: Buffer.from(DOCX_STYLES, 'utf8') });
  if (hasFooter) {
    entries.push({ name: 'word/footer1.xml', data: Buffer.from(docxFooterXml(footer), 'utf8') });
  }

  return written('docx', buildZip(entries));
}

/* -------------------------------------------------------------------------- */
/* 公共 API                                                                    */
/* -------------------------------------------------------------------------- */

/** 表格类产物：csv / xlsx / md / html / json 支持；其他格式抛错。 */
export function writeTable(
  format: ArtifactFormat,
  sheets: TableSpec[],
  spec?: { title?: string },
): WrittenFile {
  const list = sheets ?? [];
  switch (format) {
    case 'csv':
      return written('csv', Buffer.from(`\uFEFF${csvText(list, spec?.title)}`, 'utf8'));
    case 'json':
      return written('json', Buffer.from(JSON.stringify(list, null, 2), 'utf8'));
    case 'md':
      return written('md', Buffer.from(markdownTables(list, spec?.title), 'utf8'));
    case 'html':
      return written('html', Buffer.from(htmlTables(list, spec?.title), 'utf8'));
    case 'xlsx':
      return xlsxWorkbook(list);
    default:
      return unsupported(format, 'writeTable', TABLE_FORMATS);
  }
}

/** 文档类产物：docx / md / txt / html / json 支持；其他格式抛错。 */
export function writeDocument(format: ArtifactFormat, doc: DocSpec): WrittenFile {
  switch (format) {
    case 'json':
      return written('json', Buffer.from(JSON.stringify(doc, null, 2), 'utf8'));
    case 'md':
      return written('md', Buffer.from(markdownDocument(doc), 'utf8'));
    case 'txt':
      return written('txt', Buffer.from(textDocument(doc), 'utf8'));
    case 'html':
      return written('html', Buffer.from(htmlDocument(doc), 'utf8'));
    case 'docx':
      return docxDocument(doc);
    default:
      return unsupported(format, 'writeDocument', DOCUMENT_FORMATS);
  }
}
