/**
 * 零依赖 PDF 序列化器（artifact writers）。
 *
 * 用途：AI COO 的「产物导出」链路 —— 把经营报告（PdfDocSpec：标题 / 小节 / 段落 / 列表 / 表格）
 * 序列化成真正可下载的 PDF 字节流（PdfWriteResult：data + mime + ext + 字体与页码元信息），
 * 并如实告诉调用方这次渲染用的哪条字体路径、内容里有没有它画不出来的字。
 * 本模块**只依赖 Node.js 内置模块**（node:zlib + node:fs + node:path + Buffer），不引入任何第三方依赖。
 *
 * 两条渲染路径：
 * - base14（font: null 或未发现可用字体）：/Helvetica（+ /Helvetica-Bold）+ /WinAnsiEncoding，
 *   文本用 `(...) Tj` 字面量；`(` `)` `\` 与不可打印字符按 PDF 规范转义。只覆盖 Latin-1 + WinAnsi 扩展区。
 * - 嵌入 TrueType（默认自动发现）：Type0 + /Identity-H + /CIDFontType2 + /CIDToGIDMap /Identity，
 *   文本写成 UTF-16BE 的 glyph id 十六进制串 `<0048...> Tj`，同时生成 /W 宽度表与 ToUnicode CMap
 *   （可复制 / 可搜索）；字体程序作为 FontFile2 流（FlateDecode）嵌入，**默认做子集化**（见下）。
 *
 * 实现要点：
 * - 页面是 A4（595.28 × 841.89 pt），页边距 56pt，底部预留页脚带；超过页高自动分页。
 * - 自己解析 TrueType：表目录 / head(unitsPerEm, indexToLocFormat, bbox) / hhea(numberOfHMetrics,
 *   ascender, descender) / hmtx(advanceWidth) / maxp(numGlyphs) / cmap(格式 0、4、12) / name(族名) /
 *   OS/2(sCapHeight) / glyf+loca(轮廓存在性)。字体集合 .ttc 只取第 1 个字体，并把它的表重建成
 *   独立的单字体 sfnt 再嵌入（FontFile2 必须是单字体程序）；CFF/OTF（有 `CFF ` 无 `glyf`）直接判为不可用。
 * - **字体子集化**（默认开启，`subsetFont: false` 可关）：只保留文档真正用到的字形 —— 先由 cmap 把文本映射
 *   成 gid 集合，再做**复合字形闭包**（glyf 里 numberOfContours < 0 的字形由若干 component 组成，递归收集
 *   被引用的组件，否则会出现缺笔画 / 空白字），然后重建 glyf + loca 与整个 sfnt（表按 tag 升序、4 字节对齐、
 *   标准 checkSum、head.checkSumAdjustment 按规范回填）。**不做 gid 重映射**：保留 0..maxUsedGid 的槽位，
 *   未用到的槽写成零长度空字形，于是 CIDToGIDMap /Identity、cmap、/W、ToUnicode 全部无需改动。
 *   子集化过程中任何异常都会**安全回退**成整份字体嵌入（宁大勿坏），并在结果里把 subset 置 null。
 * - 换行按**字符宽度累加**：CJK / 全角字符逐字可断，拉丁词保持整体，超长单词按字符强制切分。
 * - 表格：等宽以外的按内容权重分配列宽，单元格内文字按列宽换行，细线边框 + 表头浅灰底，
 *   跨页时表头在新页重复。
 * - 全部输出**字节确定**：不读系统时间、不用随机数，FlateDecode 只作用于确定的字节流。
 *
 * 有意为之的简化（不是 bug）：
 * - 子集不做 gid 重映射（保留槽位），因此 loca 会为未用到的槽写零长度条目；cmap 原样保留，
 *   里面仍可能有指向「超出新 numGlyphs」的 gid 的映射 —— 那些码点不会被渲染，PDF 只用我们写出的 gid；
 * - 子集里 hmtx / hhea 原样保留（读到的宽度永远在表内），post 裁成 v3.0 的 32 字节最小表，
 *   丢弃 kern / GPOS / GSUB / GDEF / gasp / hdmx / LTSH / VDMX（PDF 不需要），保留 cvt /fpgm/prep；
 * - 内容流不压缩（便于人工/脚本检查），只有 FontFile2 用 FlateDecode；
 * - 不做粗体合成：嵌入字体路径下标题只用「更大字号 + 灰度差」区分，base14 路径标题走 Helvetica-Bold；
 * - 表格数字不右对齐、不做单元格截断（超宽内容按字符换行）；
 * - Info 字典不写 CreationDate / ModDate（保证同样输入两次调用输出完全相等）。
 */

import { readFileSync, readdirSync, statSync } from 'node:fs';
import path from 'node:path';
import { deflateSync } from 'node:zlib';

/* -------------------------------------------------------------------------- */
/* 公共类型                                                                    */
/* -------------------------------------------------------------------------- */

export interface PdfDocSpec {
  title?: string;
  subtitle?: string;
  sections: Array<{
    heading?: string;
    paragraphs?: string[];
    bullets?: string[];
    table?: { name?: string; columns: string[]; rows: Array<Array<string | number | boolean | null>> };
  }>;
  footer?: string;
}

export interface PdfFontInfo {
  path: string;
  familyName: string;
  /** 字形数 */
  glyphCount: number;
}

/** 字体子集化统计（`subsetFont: false`、base14 路径或子集化失败时 PdfWriteResult.subset 为 null）。 */
export interface SubsetStats {
  /** 原字体字形数 */
  glyphsTotal: number;
  /** 子集保留的字形数（= 用到的 gid ∪ 复合组件闭包） */
  glyphsKept: number;
  /** 原字体程序字节数 */
  fontBytesBefore: number;
  /** 子集后 sfnt 字节数 */
  fontBytesAfter: number;
}

export interface PdfWriteResult {
  data: Buffer;
  mime: string;
  ext: string;
  /** 实际使用的字体来源；'helvetica' 表示未嵌入字体（仅 Latin-1 安全） */
  font: 'helvetica' | 'embedded';
  fontPath?: string;
  pageCount: number;
  /** 内容中含非 Latin-1 字符但未嵌入字体时为 true —— 调用方据此降级 */
  requiresUnicodeFont: boolean;
  /** 子集化统计；关闭子集化 / 没走嵌入路径 / 子集化失败回退时为 null */
  subset?: SubsetStats | null;
}

export interface WritePdfOptions {
  fontPath?: string;
  /** 不传则自动 discoverPdfFont() */
  font?: PdfFontInfo | null;
  /** 页脚水印文字，如 "Generated by RoveFrame AI COO" */
  watermark?: string;
  /** 默认 true：只嵌入实际用到的字形。设为 false 可关闭（用于对比/排障） */
  subsetFont?: boolean;
}

type PdfSection = PdfDocSpec['sections'][number];
type PdfTableSpec = NonNullable<PdfSection['table']>;
type PdfCell = PdfTableSpec['rows'][number][number];

const PDF_MIME = 'application/pdf';
const PDF_EXT = 'pdf';

/* -------------------------------------------------------------------------- */
/* 版面常量                                                                    */
/* -------------------------------------------------------------------------- */

/** A4：595.28 × 841.89 pt */
const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN = 56;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const CONTENT_TOP = MARGIN;
/** 底部页脚带高度（页脚画在这条线以下） */
const FOOTER_HEIGHT = 24;
const CONTENT_BOTTOM = PAGE_HEIGHT - MARGIN - FOOTER_HEIGHT;
const FOOTER_BASELINE = 42;

const SIZE_TITLE = 20;
const HEIGHT_TITLE = 26;
const SIZE_SUBTITLE = 11.5;
const HEIGHT_SUBTITLE = 16;
const SIZE_HEADING = 14;
const HEIGHT_HEADING = 19;
const SIZE_BODY = 11;
const HEIGHT_BODY = 16.5;
const SIZE_TABLE_NAME = 10.5;
const HEIGHT_TABLE_NAME = 15;
const SIZE_TABLE = 10;
const HEIGHT_TABLE = 13.5;
const SIZE_FOOTER = 8.5;

const GAP_HEADING_BEFORE = 16;
const GAP_HEADING_AFTER = 7;
const GAP_PARAGRAPH = 5;
const GAP_BULLET = 2;
const GAP_TABLE = 10;
const GAP_TABLE_NAME = 4;
const CELL_PADDING_X = 5;
const CELL_PADDING_Y = 3.5;
/** 表格列宽权重上下限（按字符单元数估算，避免某列被挤没或吃掉整表） */
const COLUMN_WEIGHT_MIN = 3;
const COLUMN_WEIGHT_MAX = 24;

/** 行盒顶部到基线的近似比例（Helvetica ascender ≈ 0.718 em） */
const BASELINE_RATIO = 0.8;

const GRAY_TITLE = 0;
const GRAY_HEADING = 0;
const GRAY_BODY = 0.2;
const GRAY_SUBTITLE = 0.42;
const GRAY_FOOTER = 0.45;
const GRAY_TABLE_HEADER_BG = 0.92;
const GRAY_TABLE_BORDER = 0.62;
const GRAY_RULE = 0.75;
const LINE_WIDTH_THIN = 0.5;

/** BCP 之外的控制字符在排版里统一折叠成空格 */
const SPACE_TOKEN = ' ';

/* -------------------------------------------------------------------------- */
/* 基础工具                                                                    */
/* -------------------------------------------------------------------------- */

/** PDF 数字：最多两位小数，不用科学计数法，避免 -0。 */
function fmt(value: number): string {
  if (!Number.isFinite(value)) return '0';
  const rounded = Math.round(value * 100) / 100;
  return Object.is(rounded, -0) ? '0' : String(rounded);
}

function bufferOf(text: string): Buffer {
  return Buffer.from(text, 'latin1');
}

/** 单元格值 → 字符串（与 doc-writers 的 cellText 语义一致：null / 非有限数字 → 空串）。 */
function cellText(value: PdfCell | unknown): string {
  if (value === null || value === undefined) return '';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : '';
  if (typeof value === 'string') return value;
  return '';
}

/** 该码点是否需要按「全角 / 双宽」处理（CJK、假名、谚文、全角符号等，也是换行的断点）。 */
function isWideChar(codePoint: number): boolean {
  return (
    (codePoint >= 0x1100 && codePoint <= 0x115f) ||
    (codePoint >= 0x2e80 && codePoint <= 0xa4cf) ||
    (codePoint >= 0xac00 && codePoint <= 0xd7a3) ||
    (codePoint >= 0xf900 && codePoint <= 0xfaff) ||
    (codePoint >= 0xfe30 && codePoint <= 0xfe4f) ||
    (codePoint >= 0xff00 && codePoint <= 0xff60) ||
    (codePoint >= 0xffe0 && codePoint <= 0xffe6) ||
    (codePoint >= 0x20000 && codePoint <= 0x3fffd)
  );
}

/** 文本的「字符单元数」：全角 2、其余 1（只用于表格列宽估算）。 */
function unitsOf(text: string): number {
  let units = 0;
  for (const ch of text) units += isWideChar(ch.codePointAt(0) ?? 0) ? 2 : 1;
  return units;
}

function utf16Hex(codePoint: number): string {
  if (codePoint <= 0xffff) return codePoint.toString(16).padStart(4, '0');
  const value = codePoint - 0x10000;
  const high = 0xd800 + (value >> 10);
  const low = 0xdc00 + (value & 0x3ff);
  return `${high.toString(16).padStart(4, '0')}${low.toString(16).padStart(4, '0')}`;
}

/* -------------------------------------------------------------------------- */
/* base14（Helvetica）宽度与 WinAnsiEncoding                                   */
/* -------------------------------------------------------------------------- */

/** Helvetica 的 ASCII 宽度（单位 1/1000 em，索引 = 码点 - 32）。 */
const HELVETICA_WIDTHS: readonly number[] = [
  278, 278, 355, 556, 556, 889, 667, 191, 333, 333, 389, 584, 278, 333, 278, 278,
  556, 556, 556, 556, 556, 556, 556, 556, 556, 556, 278, 278, 584, 584, 584, 556,
  1015, 667, 667, 722, 722, 667, 611, 778, 722, 278, 500, 667, 556, 833, 722, 778,
  667, 778, 722, 667, 611, 722, 667, 944, 667, 667, 611, 278, 278, 278, 469, 556,
  333, 556, 556, 500, 556, 556, 278, 556, 556, 222, 222, 500, 222, 833, 556, 556,
  556, 556, 333, 500, 278, 556, 500, 722, 500, 500, 500, 334, 260, 334, 584,
];

/** Helvetica-Bold 的 ASCII 宽度（单位 1/1000 em）。 */
const HELVETICA_BOLD_WIDTHS: readonly number[] = [
  278, 333, 474, 556, 556, 889, 722, 238, 333, 333, 389, 584, 278, 333, 278, 278,
  556, 556, 556, 556, 556, 556, 556, 556, 556, 556, 333, 333, 584, 584, 584, 611,
  975, 722, 722, 722, 722, 667, 611, 778, 722, 278, 556, 722, 611, 833, 722, 778,
  667, 778, 722, 667, 611, 722, 667, 944, 667, 667, 611, 333, 278, 333, 584, 556,
  333, 556, 611, 556, 611, 556, 333, 611, 611, 278, 278, 556, 278, 889, 611, 611,
  611, 611, 389, 556, 333, 611, 556, 778, 556, 556, 500, 389, 280, 389, 584,
];

/** ASCII 之外的 Latin-1 用这个近似宽度（Helvetica 的小写 ≈ 556 / 大写 ≈ 667）。 */
const HELVETICA_DEFAULT_WIDTH = 556;
const HELVETICA_BOLD_DEFAULT_WIDTH = 611;

/** Unicode 码点 → WinAnsiEncoding 字节（0x80–0x9F 区间的重映射，含引号 / 破折号 / 项目符号）。 */
const WIN_ANSI_HIGH: ReadonlyMap<number, number> = new Map<number, number>([
  [0x20ac, 0x80], [0x201a, 0x82], [0x0192, 0x83], [0x201e, 0x84], [0x2026, 0x85],
  [0x2020, 0x86], [0x2021, 0x87], [0x02c6, 0x88], [0x2030, 0x89], [0x0160, 0x8a],
  [0x2039, 0x8b], [0x0152, 0x8c], [0x017d, 0x8e], [0x2018, 0x91], [0x2019, 0x92],
  [0x201c, 0x93], [0x201d, 0x94], [0x2022, 0x95], [0x2013, 0x96], [0x2014, 0x97],
  [0x02dc, 0x98], [0x2122, 0x99], [0x0161, 0x9a], [0x203a, 0x9b], [0x0153, 0x9c],
  [0x017e, 0x9e], [0x0178, 0x9f],
]);

/** 码点是否落在可打印区间。 */
function isPrintableAscii(codePoint: number): boolean {
  return codePoint >= 0x20 && codePoint <= 0x7e;
}

function isLatin1(codePoint: number): boolean {
  return codePoint >= 0xa0 && codePoint <= 0xff;
}

/** Unicode 码点 → WinAnsi 字节；无法表示时回落 `?`。 */
function winAnsiByte(codePoint: number): number {
  if (codePoint === 0x09 || codePoint === 0x0a || codePoint === 0x0d) return 0x20;
  if (isPrintableAscii(codePoint) || isLatin1(codePoint)) return codePoint;
  return WIN_ANSI_HIGH.get(codePoint) ?? 0x3f;
}

/**
 * 内容里是否有 base14 Helvetica 无法表示的字符（CJK、emoji、重音外的符号等）。
 * 判据是「码点在 Latin-1 / WinAnsi 之外」：C0 控制字符（< 0x20）与 DEL 属于 ASCII 区，
 * 排版时会被折成空格或 `?` 清掉，不算「缺字体」，因此不触发降级标记。
 */
export function needsUnicodeFont(text: string): boolean {
  for (const ch of String(text ?? '')) {
    const codePoint = ch.codePointAt(0) ?? 0;
    if (codePoint < 0x80) continue;
    if (isLatin1(codePoint)) continue;
    if (WIN_ANSI_HIGH.has(codePoint)) continue;
    return true;
  }
  return false;
}

function base14Width(codePoint: number, bold: boolean): number {
  if (codePoint >= 32 && codePoint <= 126) {
    const table = bold ? HELVETICA_BOLD_WIDTHS : HELVETICA_WIDTHS;
    return table[codePoint - 32];
  }
  return bold ? HELVETICA_BOLD_DEFAULT_WIDTH : HELVETICA_DEFAULT_WIDTH;
}

/** Helvetica 的 /Widths（FirstChar 32、LastChar 255）。 */
function base14WidthArray(bold: boolean): string {
  const table = bold ? HELVETICA_BOLD_WIDTHS : HELVETICA_WIDTHS;
  const fallback = bold ? HELVETICA_BOLD_DEFAULT_WIDTH : HELVETICA_DEFAULT_WIDTH;
  const widths: number[] = [];
  for (let codePoint = 32; codePoint <= 255; codePoint += 1) {
    widths.push(codePoint <= 126 ? table[codePoint - 32] : fallback);
  }
  return `[ ${widths.join(' ')} ]`;
}

/* -------------------------------------------------------------------------- */
/* TrueType 解析                                                               */
/* -------------------------------------------------------------------------- */

interface TableRecord {
  offset: number;
  length: number;
}

interface EmbeddedFont {
  /** 加载来源路径 */
  path: string;
  /** 独立 sfnt（单字体 TTF）字节，直接作为 FontFile2 */
  program: Buffer;
  /** FlateDecode 之后的整份字体程序（懒计算：开了子集化就不必压缩这十几 MB） */
  programCompressed?: Buffer;
  familyName: string;
  postScriptName: string;
  glyphCount: number;
  unitsPerEm: number;
  indexToLocFormat: number;
  ascender: number;
  descender: number;
  capHeight: number;
  bbox: [number, number, number, number];
  numberOfHMetrics: number;
  /** 每个 glyph 的 advanceWidth（em 单位由 unitsPerEm 决定） */
  advanceWidths: number[];
  /** Unicode 码点 → glyph id */
  cmap: Map<number, number>;
  /** glyph id → 代表码点（生成 ToUnicode 用） */
  glyphToCodePoint: Map<number, number>;
}

const TTC_TAG = 0x74746366; // 'ttcf'
const CFF_TAG = 'CFF ';
const SFNT_TRUE = 0x74727565; // 'true'
const SFNT_VERSION_1 = 0x00010000;

/** 必需表：缺任何一个（或有 CFF 无 glyf）都不是可嵌入的 TrueType 轮廓字体。 */
const REQUIRED_TABLES: readonly string[] = ['cmap', 'head', 'hhea', 'hmtx', 'maxp', 'glyf', 'loca'];

/** 单个字体最多接受的字形数（防止畸形字体把内存打爆）。 */
const MAX_GLYPHS = 200000;
/** cmap 最多接受的映射条数。 */
const MAX_CMAP_ENTRIES = 200000;

const FONT_EXTENSIONS: readonly string[] = ['.ttf', '.ttc', '.otf'];
/** 已解析字体缓存（FlateDecode 过的字体程序很贵，重复导出务必命中缓存） */
const FONT_CACHE = new Map<string, EmbeddedFont>();
const FONT_CACHE_LIMIT = 4;

function u16(buffer: Buffer, offset: number): number {
  return buffer.readUInt16BE(offset);
}

function i16(buffer: Buffer, offset: number): number {
  return buffer.readInt16BE(offset);
}

function u32(buffer: Buffer, offset: number): number {
  return buffer.readUInt32BE(offset);
}

function readTableTag(buffer: Buffer, offset: number): string {
  return buffer.toString('latin1', offset, offset + 4);
}

/** 读 sfnt 表目录；越界或畸形的表记录直接跳过（不抛错）。 */
function readTableDirectory(buffer: Buffer, fontOffset: number): Map<string, TableRecord> {
  const numTables = u16(buffer, fontOffset + 4);
  if (numTables <= 0 || numTables > 512) throw new Error('sfnt 表数量异常');
  const tables = new Map<string, TableRecord>();
  for (let i = 0; i < numTables; i += 1) {
    const record = fontOffset + 12 + i * 16;
    const tag = readTableTag(buffer, record);
    const offset = u32(buffer, record + 8);
    const length = u32(buffer, record + 12);
    if (offset + length > buffer.length) continue;
    if (!tables.has(tag)) tables.set(tag, { offset, length });
  }
  return tables;
}

function tableData(buffer: Buffer, tables: Map<string, TableRecord>, tag: string): Buffer | null {
  const record = tables.get(tag);
  if (record === undefined) return null;
  return buffer.subarray(record.offset, record.offset + record.length);
}

/** sfnt 标准累加校验和（4 字节大端求和，末尾不足 4 字节按 0 补齐）。 */
function sfntChecksum(data: Buffer): number {
  const padded = data.length % 4 === 0 ? data : Buffer.concat([data, Buffer.alloc(4 - (data.length % 4))]);
  let sum = 0;
  for (let i = 0; i < padded.length; i += 4) {
    sum = (sum + padded.readUInt32BE(i)) % 4294967296;
  }
  return sum;
}

interface SfntTable {
  tag: string;
  data: Buffer;
}

/**
 * 组装单字体 sfnt：表按 tag 升序、偏移 4 字节对齐、checkSum 用标准累加算法，
 * 最后按规范回填 head.checkSumAdjustment（0xB1B0AFBA - 整文件校验和）。
 */
function buildSfnt(version: number, tables: SfntTable[]): Buffer {
  const sorted = [...tables].sort((a, b) => (a.tag < b.tag ? -1 : a.tag > b.tag ? 1 : 0));
  const numTables = sorted.length;

  const header = Buffer.alloc(12);
  header.writeUInt32BE(version === SFNT_TRUE ? version : SFNT_VERSION_1, 0);
  header.writeUInt16BE(numTables, 4);
  const entrySelector = Math.floor(Math.log2(numTables));
  const searchRange = 16 * 2 ** entrySelector;
  header.writeUInt16BE(searchRange, 6);
  header.writeUInt16BE(entrySelector, 8);
  header.writeUInt16BE(numTables * 16 - searchRange, 10);

  const directory = Buffer.alloc(numTables * 16);
  const chunks: Buffer[] = [header, directory];
  let dataOffset = 12 + numTables * 16;
  let headOffset = -1;

  for (const [index, table] of sorted.entries()) {
    let data = table.data;
    if (table.tag === 'head' && data.length >= 12) {
      // checkSumAdjustment 先置 0 参与 checksum 计算，最后整文件回填
      data = Buffer.from(data);
      data.writeUInt32BE(0, 8);
      headOffset = dataOffset;
    }
    const record = index * 16;
    directory.write(table.tag, record, 4, 'latin1');
    directory.writeUInt32BE(sfntChecksum(data), record + 4);
    directory.writeUInt32BE(dataOffset, record + 8);
    directory.writeUInt32BE(data.length, record + 12);
    const padding = (4 - (data.length % 4)) % 4;
    const padded = padding > 0 ? Buffer.concat([data, Buffer.alloc(padding)]) : data;
    chunks.push(padded);
    dataOffset += padded.length;
  }

  const file = Buffer.concat(chunks);
  if (headOffset >= 0) {
    file.writeUInt32BE((0xb1b0afba - sfntChecksum(file)) >>> 0, headOffset + 8);
  }
  return file;
}

/**
 * 把字体集合（.ttc）里的第 1 个字体重建成独立的单字体 sfnt。
 * FontFile2 必须是「单字体」程序，直接塞 ttcf 文件在严格阅读器里不合法。
 */
function buildStandaloneTtf(buffer: Buffer, fontOffset: number, tables: Map<string, TableRecord>): Buffer {
  const version = u32(buffer, fontOffset);
  const entries = [...tables.entries()].map(([tag, record]) => ({
    tag,
    data: buffer.subarray(record.offset, record.offset + record.length),
  }));
  return buildSfnt(version, entries);
}

/** 解析 cmap 子表（支持格式 0 / 4 / 12），返回 码点 → glyph id。 */
function parseCmapTable(cmap: Buffer): Map<number, number> {
  const result = new Map<number, number>();
  const numSubtables = u16(cmap, 2);
  const subtables: Array<{ score: number; offset: number }> = [];
  for (let i = 0; i < numSubtables; i += 1) {
    const record = 4 + i * 8;
    const platform = u16(cmap, record);
    const encoding = u16(cmap, record + 2);
    const offset = u32(cmap, record + 4);
    if (offset + 4 > cmap.length) continue;
    let score = 0;
    if (platform === 3 && encoding === 10) score = 5;
    else if (platform === 0 && (encoding === 4 || encoding === 6)) score = 4;
    else if (platform === 3 && encoding === 1) score = 3;
    else if (platform === 0) score = 2;
    else if (platform === 1 && encoding === 0) score = 1;
    if (score > 0) subtables.push({ score, offset });
  }
  subtables.sort((a, b) => b.score - a.score);

  for (const subtable of subtables) {
    if (result.size >= MAX_CMAP_ENTRIES) break;
    try {
      const format = u16(cmap, subtable.offset);
      if (format === 0) parseCmapFormat0(cmap, subtable.offset, result);
      else if (format === 4) parseCmapFormat4(cmap, subtable.offset, result);
      else if (format === 12) parseCmapFormat12(cmap, subtable.offset, result);
    } catch {
      continue;
    }
  }
  return result;
}

function parseCmapFormat0(cmap: Buffer, base: number, result: Map<number, number>): void {
  const start = base + 6;
  if (start + 256 > cmap.length) return;
  for (let code = 0; code < 256; code += 1) {
    const gid = cmap.readUInt8(start + code);
    if (gid !== 0 && !result.has(code)) result.set(code, gid);
  }
}

function parseCmapFormat4(cmap: Buffer, base: number, result: Map<number, number>): void {
  const segCountX2 = u16(cmap, base + 6);
  const segCount = segCountX2 / 2;
  if (segCount <= 0 || segCount > 65535) return;
  const endCode = base + 14;
  const startCode = endCode + segCountX2 + 2;
  const idDelta = startCode + segCountX2;
  const idRangeOffset = idDelta + segCountX2;
  for (let i = 0; i < segCount; i += 1) {
    const end = u16(cmap, endCode + i * 2);
    const start = u16(cmap, startCode + i * 2);
    const delta = i16(cmap, idDelta + i * 2);
    const rangeOffset = u16(cmap, idRangeOffset + i * 2);
    if (start > end) continue;
    for (let code = start; code <= end; code += 1) {
      if (code === 0xffff || result.size >= MAX_CMAP_ENTRIES) break;
      let gid: number;
      if (rangeOffset === 0) {
        gid = (code + delta) & 0xffff;
      } else {
        const index = idRangeOffset + i * 2 + rangeOffset + (code - start) * 2;
        if (index + 2 > cmap.length) break;
        const raw = u16(cmap, index);
        gid = raw === 0 ? 0 : (raw + delta) & 0xffff;
      }
      if (gid !== 0 && !result.has(code)) result.set(code, gid);
    }
  }
}

function parseCmapFormat12(cmap: Buffer, base: number, result: Map<number, number>): void {
  const numGroups = u32(cmap, base + 12);
  if (numGroups > MAX_CMAP_ENTRIES) return;
  for (let i = 0; i < numGroups; i += 1) {
    const group = base + 16 + i * 12;
    if (group + 12 > cmap.length) return;
    const start = u32(cmap, group);
    const end = u32(cmap, group + 4);
    const startGlyph = u32(cmap, group + 8);
    if (start > end || end - start > 0x10ffff) continue;
    for (let code = start; code <= end; code += 1) {
      if (result.size >= MAX_CMAP_ENTRIES) return;
      const gid = startGlyph + (code - start);
      if (gid !== 0 && !result.has(code)) result.set(code, gid);
    }
  }
}

/** 从 name 表取族名 / PostScript 名（优先 Windows(3) 的 UTF-16BE 记录）。 */
function parseFontNames(name: Buffer, fallback: string): { familyName: string; postScriptName: string } {
  let familyName = '';
  let postScriptName = '';
  let familyScore = -1;
  let postScriptScore = -1;
  const count = u16(name, 2);
  const stringOffset = u16(name, 4);
  for (let i = 0; i < count; i += 1) {
    const record = 6 + i * 12;
    if (record + 12 > name.length) break;
    const platform = u16(name, record);
    const nameId = u16(name, record + 6);
    const length = u16(name, record + 8);
    const offset = u16(name, record + 10);
    if (nameId !== 1 && nameId !== 6) continue;
    const start = stringOffset + offset;
    if (start + length > name.length) continue;
    const raw = name.subarray(start, start + length);
    const decoded = platform === 3 || platform === 0 ? decodeUtf16Be(raw) : raw.toString('latin1');
    const value = decoded.replace(/\u0000/g, '').trim();
    if (value === '') continue;
    const score = platform === 3 ? 3 : platform === 0 ? 2 : 1;
    if (nameId === 1 && score > familyScore) {
      familyScore = score;
      familyName = value;
    }
    if (nameId === 6 && score > postScriptScore) {
      postScriptScore = score;
      postScriptName = value;
    }
  }
  const family = familyName !== '' ? familyName : postScriptName !== '' ? postScriptName : fallback;
  const postScript = postScriptName !== '' ? postScriptName : family;
  return { familyName: family, postScriptName: postScript };
}

function decodeUtf16Be(raw: Buffer): string {
  const swapped = Buffer.alloc(raw.length);
  for (let i = 0; i + 1 < raw.length; i += 2) {
    swapped[i] = raw[i + 1];
    swapped[i + 1] = raw[i];
  }
  return swapped.toString('utf16le');
}

/** PDF 名字对象里不允许出现分隔符 / 非 ASCII，做一次保守清洗。 */
function sanitizePostScriptName(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9+-]/g, '');
  return cleaned === '' ? 'EmbeddedFont' : cleaned.slice(0, 60);
}

/**
 * 解析一个 TrueType 字体文件（.ttf 或 .ttc 的第 1 个字体）。
 * 任何不满足「可嵌入 glyf 轮廓」条件的情况都返回 null，由调用方跳过继续找下一个。
 */
function parseTrueTypeFont(buffer: Buffer, filePath: string): EmbeddedFont | null {
  if (buffer.length < 12) return null;
  let fontOffset = 0;
  let program = buffer;
  if (u32(buffer, 0) === TTC_TAG) {
    const numFonts = u32(buffer, 8);
    if (numFonts < 1) return null;
    fontOffset = u32(buffer, 12);
    if (fontOffset + 12 > buffer.length) return null;
  }

  const tables = readTableDirectory(buffer, fontOffset);
  for (const required of REQUIRED_TABLES) {
    if (!tables.has(required)) return null;
  }
  if (readTableTag(buffer, fontOffset) === 'OTTO') return null;

  const head = tableData(buffer, tables, 'head');
  const hhea = tableData(buffer, tables, 'hhea');
  const maxp = tableData(buffer, tables, 'maxp');
  const hmtx = tableData(buffer, tables, 'hmtx');
  const cmapTable = tableData(buffer, tables, 'cmap');
  const locaTable = tableData(buffer, tables, 'loca');
  const cff = tableData(buffer, tables, CFF_TAG);
  if (head === null || hhea === null || maxp === null || hmtx === null || cmapTable === null) return null;
  if (locaTable === null || cff !== null) return null;
  if (head.length < 54 || hhea.length < 36 || maxp.length < 6) return null;

  const unitsPerEm = u16(head, 18);
  const indexToLocFormat = i16(head, 50);
  if (unitsPerEm === 0 || (indexToLocFormat !== 0 && indexToLocFormat !== 1)) return null;

  const glyphCount = u16(maxp, 4);
  if (glyphCount <= 0 || glyphCount > MAX_GLYPHS) return null;

  // loca 长度必须与 numGlyphs + 1 个偏移一致，才算真的带 glyf 轮廓
  const locaEntrySize = indexToLocFormat === 0 ? 2 : 4;
  if (locaTable.length < (glyphCount + 1) * locaEntrySize) return null;

  const numberOfHMetrics = u16(hhea, 34);
  if (numberOfHMetrics <= 0 || numberOfHMetrics > glyphCount) return null;

  const advanceWidths: number[] = new Array<number>(glyphCount);
  let lastAdvance = 0;
  for (let gid = 0; gid < glyphCount; gid += 1) {
    if (gid < numberOfHMetrics) {
      const offset = gid * 4;
      if (offset + 2 > hmtx.length) return null;
      lastAdvance = u16(hmtx, offset);
    }
    advanceWidths[gid] = lastAdvance;
  }

  const cmap = parseCmapTable(cmapTable);
  if (cmap.size === 0) return null;

  // glyph → 码点 反向表：按码点升序取第一个，保证 ToUnicode 生成确定
  const glyphToCodePoint = new Map<number, number>();
  const codePoints = [...cmap.keys()].sort((a, b) => a - b);
  for (const codePoint of codePoints) {
    const gid = cmap.get(codePoint) ?? 0;
    if (gid >= glyphCount) continue;
    if (!glyphToCodePoint.has(gid)) glyphToCodePoint.set(gid, codePoint);
  }

  if (fontOffset === 0) {
    program = buffer;
  } else {
    program = buildStandaloneTtf(buffer, fontOffset, tables);
  }

  const nameTable = tableData(buffer, tables, 'name');
  const fallbackName = path.basename(filePath).replace(/\.[^.]+$/, '');
  const names = nameTable === null ? { familyName: fallbackName, postScriptName: fallbackName } : parseFontNames(nameTable, fallbackName);

  const os2 = tableData(buffer, tables, 'OS/2');
  const ascender = i16(hhea, 4);
  const rawDescender = i16(hhea, 6);
  let capHeight = 0;
  if (os2 !== null && os2.length >= 90 && u16(os2, 0) >= 2) {
    capHeight = u16(os2, 88);
  }
  if (capHeight <= 0) capHeight = Math.round(ascender * 0.7);

  return {
    path: filePath,
    program,
    familyName: names.familyName,
    postScriptName: sanitizePostScriptName(names.postScriptName),
    glyphCount,
    unitsPerEm,
    indexToLocFormat,
    ascender,
    descender: rawDescender > 0 ? -rawDescender : rawDescender,
    capHeight,
    bbox: [i16(head, 36), i16(head, 38), i16(head, 40), i16(head, 42)],
    numberOfHMetrics,
    advanceWidths,
    cmap,
    glyphToCodePoint,
  };
}

/* -------------------------------------------------------------------------- */
/* 字体发现                                                                    */
/* -------------------------------------------------------------------------- */

function cacheFont(font: EmbeddedFont): void {
  if (FONT_CACHE.size >= FONT_CACHE_LIMIT) {
    const oldest = FONT_CACHE.keys().next();
    if (!oldest.done) FONT_CACHE.delete(oldest.value);
  }
  FONT_CACHE.set(font.path, font);
}

/** 读取 + 解析字体文件；读不到 / 解析失败返回 null（绝不抛错）。 */
function loadFont(filePath: string): EmbeddedFont | null {
  const resolved = path.resolve(filePath);
  const cached = FONT_CACHE.get(resolved);
  if (cached !== undefined) return cached;
  let font: EmbeddedFont | null = null;
  try {
    if (statSync(resolved).isFile()) {
      font = parseTrueTypeFont(readFileSync(resolved), resolved);
    }
  } catch {
    font = null;
  }
  if (font !== null) cacheFont(font);
  return font;
}

/** <cwd>/public/fonts 下的字体文件（按文件名排序，保证发现顺序确定）。 */
function projectFontCandidates(): string[] {
  const dir = path.join(process.cwd(), 'public', 'fonts');
  let names: string[] = [];
  try {
    names = readdirSync(dir).sort();
  } catch {
    return [];
  }
  return names
    .filter((name) => FONT_EXTENSIONS.includes(path.extname(name).toLowerCase()))
    .map((name) => path.join(dir, name));
}

/** 常见 CJK / 回退字体文件名（Linux 字体目录里的匹配模式）。 */
const LINUX_FONT_PATTERNS: readonly RegExp[] = [
  /^NotoSansCJK/i,
  /^NotoSerifCJK/i,
  /^NotoSansSC/i,
  /^NotoSerifSC/i,
  /^SourceHanSans/i,
  /^SourceHanSerif/i,
  /^wqy-/i,
  /^DroidSansFallback/i,
  /^ukai/i,
  /^uming/i,
];

const LINUX_FONT_ROOTS: readonly string[] = [
  '/usr/share/fonts',
  '/usr/local/share/fonts',
  '/usr/share/fonts/truetype',
  '/usr/share/fonts/opentype',
];

const MAX_FONT_SCAN_DEPTH = 4;
const MAX_FONT_SCAN_RESULTS = 60;

function scanFontDir(dir: string, depth: number, out: string[]): void {
  if (depth > MAX_FONT_SCAN_DEPTH || out.length >= MAX_FONT_SCAN_RESULTS) return;
  let entries: string[] = [];
  try {
    entries = readdirSync(dir).sort();
  } catch {
    return;
  }
  for (const entry of entries) {
    if (out.length >= MAX_FONT_SCAN_RESULTS) return;
    const full = path.join(dir, entry);
    let directory = false;
    try {
      directory = statSync(full).isDirectory();
    } catch {
      continue;
    }
    if (directory) {
      scanFontDir(full, depth + 1, out);
      continue;
    }
    if (!FONT_EXTENSIONS.includes(path.extname(entry).toLowerCase())) continue;
    if (LINUX_FONT_PATTERNS.some((pattern) => pattern.test(entry))) out.push(full);
  }
}

function linuxFontCandidates(): string[] {
  const out: string[] = [];
  for (const root of LINUX_FONT_ROOTS) scanFontDir(root, 0, out);
  return out;
}

/** 常见 Windows 字体（顺序即优先级：雅黑 → 黑体 → 宋体 → Arial 兜底）。 */
function windowsFontCandidates(): string[] {
  const dir = path.join(process.env.WINDIR ?? process.env.SystemRoot ?? 'C:\\Windows', 'Fonts');
  return ['msyh.ttc', 'simhei.ttf', 'simsun.ttc', 'arial.ttf'].map((name) => path.join(dir, name));
}

/** 按 ①explicitPath ②RF_PDF_FONT ③public/fonts ④Linux ⑤Windows 收集候选（去重、顺序稳定）。 */
function fontCandidates(explicitPath?: string): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  const add = (candidate: string | undefined): void => {
    if (candidate === undefined || candidate.trim() === '') return;
    const resolved = path.resolve(candidate.trim());
    if (seen.has(resolved)) return;
    seen.add(resolved);
    out.push(resolved);
  };
  add(explicitPath);
  add(process.env.RF_PDF_FONT);
  for (const candidate of projectFontCandidates()) add(candidate);
  for (const candidate of linuxFontCandidates()) add(candidate);
  for (const candidate of windowsFontCandidates()) add(candidate);
  return out;
}

/**
 * 发现可用的 CJK/Unicode TrueType 字体。
 * 顺序：① 参数 explicitPath ② env RF_PDF_FONT ③ <cwd>/public/fonts 下的 .ttf / .otf / .ttc
 *      ④ 常见 Linux 字体目录（NotoSansCJK*、wqy-*、DroidSansFallback* 等）
 *      ⑤ 常见 Windows 字体（msyh.ttc、simhei.ttf、simsun.ttc、arial.ttf）
 * 都找不到返回 null。读不到 / 解析失败（含 CFF/OTF）会跳过并继续找下一个，绝不抛错中断。
 */
export function discoverPdfFont(explicitPath?: string): PdfFontInfo | null {
  for (const candidate of fontCandidates(explicitPath)) {
    const font = loadFont(candidate);
    if (font !== null) {
      return { path: candidate, familyName: font.familyName, glyphCount: font.glyphCount };
    }
  }
  return null;
}

/* -------------------------------------------------------------------------- */
/* 字体子集化                                                                  */
/* -------------------------------------------------------------------------- */

/**
 * 子集里保留的表（PDF 只需要这些）：
 * - glyf / loca 重建，head / maxp 就地改写，post 裁成 v3.0；
 * - cmap 原样保留（gid 不重映射，映射依旧有效），hmtx / hhea 原样保留（读到的宽度一定在表内）；
 * - 保留 cvt / fpgm / prep：体积很小，但能让查看器继续做 hinting，避免栅格化差异；
 * - kern / GPOS / GSUB / GDEF / gasp / hdmx / LTSH / VDMX 等全部丢弃（PDF 里由 Tm 自己排版，用不到）。
 */
const SUBSET_KEEP_TABLES: readonly string[] = [
  'OS/2',
  'cmap',
  'cvt ',
  'fpgm',
  'glyf',
  'head',
  'hhea',
  'hmtx',
  'loca',
  'maxp',
  'name',
  'post',
  'prep',
];

/* 复合字形 component 的 flag（OpenType glyf 规范） */
const COMPONENT_ARG_1_AND_2_ARE_WORDS = 0x0001;
const COMPONENT_WE_HAVE_A_SCALE = 0x0008;
const COMPONENT_MORE_COMPONENTS = 0x0020;
const COMPONENT_WE_HAVE_AN_X_AND_Y_SCALE = 0x0040;
const COMPONENT_WE_HAVE_A_TWO_BY_TWO = 0x0080;

/** loca 表 → numGlyphs + 1 个 glyf 偏移。表长不足直接抛错（交给上层回退）。 */
function readLoca(loca: Buffer, numGlyphs: number, indexToLocFormat: number): number[] {
  const entrySize = indexToLocFormat === 0 ? 2 : 4;
  if (loca.length < (numGlyphs + 1) * entrySize) throw new Error('loca 表长度不足');
  const offsets: number[] = [];
  for (let gid = 0; gid <= numGlyphs; gid += 1) {
    offsets.push(indexToLocFormat === 0 ? u16(loca, gid * 2) * 2 : u32(loca, gid * 4));
  }
  return offsets;
}

/**
 * 复合字形（numberOfContours < 0）引用的组件 gid 列表。
 * 每个 component 是「flags(2) + glyphIndex(2) + args + 可选变换」，args 与变换的长度由 flag 决定；
 * ARGS_ARE_XY_VALUES 只影响参数语义、不影响长度，WE_HAVE_INSTRUCTIONS 只影响最后一个 component
 * 之后的附加数据，所以这里按 flag 累加长度直到 MORE_COMPONENTS 清零即可。
 */
function compositeGlyphComponents(glyf: Buffer, start: number, end: number): number[] {
  const components: number[] = [];
  let offset = start + 10; // numberOfContours(2) + xMin/yMin/xMax/yMax(8)
  while (offset + 4 <= end) {
    const flags = u16(glyf, offset);
    components.push(u16(glyf, offset + 2));
    offset += 4;
    offset += (flags & COMPONENT_ARG_1_AND_2_ARE_WORDS) !== 0 ? 4 : 2;
    if ((flags & COMPONENT_WE_HAVE_A_SCALE) !== 0) offset += 2;
    else if ((flags & COMPONENT_WE_HAVE_AN_X_AND_Y_SCALE) !== 0) offset += 4;
    else if ((flags & COMPONENT_WE_HAVE_A_TWO_BY_TWO) !== 0) offset += 8;
    if ((flags & COMPONENT_MORE_COMPONENTS) === 0) break;
  }
  return components;
}

/** post 表裁剪成 version 3.0 的 32 字节最小表（无字形名），保留斜体角 / 下划线度量。 */
function minimalPostTable(post: Buffer | null): Buffer {
  const out = Buffer.alloc(32);
  out.writeUInt32BE(0x00030000, 0);
  if (post !== null && post.length >= 16) post.copy(out, 4, 4, 16);
  return out;
}

/**
 * 生成字体子集：只保留用到的字形 + 复合组件闭包，重建 glyf / loca / sfont 表目录。
 * gid 保持不变（不做重映射），保留 0..maxUsedGid 的槽位，未用到的槽写零长度空字形。
 * 任何异常都向上抛，由 writePdf 回退成整份字体嵌入。
 */
function subsetFontProgram(program: Buffer, usedGids: Set<number>): { program: Buffer; stats: SubsetStats } {
  const tables = readTableDirectory(program, 0);
  const head = tableData(program, tables, 'head');
  const maxp = tableData(program, tables, 'maxp');
  const hhea = tableData(program, tables, 'hhea');
  const hmtx = tableData(program, tables, 'hmtx');
  const cmap = tableData(program, tables, 'cmap');
  const loca = tableData(program, tables, 'loca');
  const glyf = tableData(program, tables, 'glyf');
  if (head === null || head.length < 54) throw new Error('head 表缺失或过短');
  if (maxp === null || maxp.length < 6) throw new Error('maxp 表缺失或过短');
  if (hhea === null || hmtx === null || cmap === null) throw new Error('hhea / hmtx / cmap 表缺失');
  if (loca === null || glyf === null) throw new Error('glyf / loca 表缺失');

  const numGlyphs = u16(maxp, 4);
  const indexToLocFormat = i16(head, 50);
  if (numGlyphs <= 0 || (indexToLocFormat !== 0 && indexToLocFormat !== 1)) {
    throw new Error('head / maxp 字段异常');
  }
  const offsets = readLoca(loca, numGlyphs, indexToLocFormat);

  // ① 用到的 gid + .notdef，再做复合组件递归闭包
  const kept = new Set<number>();
  const pending: number[] = [0];
  for (const gid of usedGids) {
    if (gid >= 0 && gid < numGlyphs) pending.push(gid);
  }
  while (pending.length > 0) {
    const gid = pending.pop();
    if (gid === undefined) break;
    if (kept.has(gid)) continue;
    kept.add(gid);
    const start = offsets[gid];
    if (start > glyf.length) throw new Error(`glyf 偏移越界（gid ${gid}）`);
    const end = Math.min(offsets[gid + 1], glyf.length);
    if (end < start) throw new Error(`glyf 区间非法（gid ${gid}）`);
    if (end > start && i16(glyf, start) < 0) {
      for (const component of compositeGlyphComponents(glyf, start, end)) {
        if (component >= 0 && component < numGlyphs && !kept.has(component)) pending.push(component);
      }
    }
  }

  let maxUsedGid = 0;
  for (const gid of kept) maxUsedGid = Math.max(maxUsedGid, gid);
  const newGlyphCount = maxUsedGid + 1;

  // ② 重建 glyf：每个字形 4 字节对齐（short loca 只要求偶数），未用到的槽是零长度空字形
  const glyphChunks: Buffer[] = [];
  const newOffsets: number[] = [];
  let glyfLength = 0;
  for (let gid = 0; gid < newGlyphCount; gid += 1) {
    newOffsets.push(glyfLength);
    if (!kept.has(gid)) continue;
    const start = offsets[gid];
    const end = Math.min(offsets[gid + 1], glyf.length);
    if (end <= start) continue;
    let data = Buffer.from(glyf.subarray(start, end));
    const padding = (4 - (data.length % 4)) % 4;
    if (padding > 0) data = Buffer.concat([data, Buffer.alloc(padding)]);
    glyphChunks.push(data);
    glyfLength += data.length;
  }
  newOffsets.push(glyfLength);
  const newGlyf = Buffer.concat(glyphChunks, glyfLength);

  // ③ 重建 loca：short 只能表示 offset / 2，所以总长必须 <= 0xFFFF * 2
  const useShortLoca = glyfLength <= 0xffff * 2;
  const newLoca = Buffer.alloc((newGlyphCount + 1) * (useShortLoca ? 2 : 4));
  for (const [index, offset] of newOffsets.entries()) {
    if (useShortLoca) newLoca.writeUInt16BE(offset / 2, index * 2);
    else newLoca.writeUInt32BE(offset, index * 4);
  }

  const newHead = Buffer.from(head);
  newHead.writeInt16BE(useShortLoca ? 0 : 1, 50);
  const newMaxp = Buffer.from(maxp);
  newMaxp.writeUInt16BE(newGlyphCount, 4);

  const subsetTables: SfntTable[] = [];
  for (const tag of SUBSET_KEEP_TABLES) {
    if (tag === 'glyf') subsetTables.push({ tag, data: newGlyf });
    else if (tag === 'loca') subsetTables.push({ tag, data: newLoca });
    else if (tag === 'head') subsetTables.push({ tag, data: newHead });
    else if (tag === 'maxp') subsetTables.push({ tag, data: newMaxp });
    else if (tag === 'post') subsetTables.push({ tag, data: minimalPostTable(tableData(program, tables, 'post')) });
    else {
      const data = tableData(program, tables, tag);
      if (data !== null) subsetTables.push({ tag, data });
    }
  }

  const subsetProgram = buildSfnt(SFNT_VERSION_1, subsetTables);
  return {
    program: subsetProgram,
    stats: {
      glyphsTotal: numGlyphs,
      glyphsKept: kept.size,
      fontBytesBefore: program.length,
      fontBytesAfter: subsetProgram.length,
    },
  };
}

/** FontFile2 的 FlateDecode 结果：整份字体程序走缓存（十几 MB，压一次就够），子集程序现压（很小）。 */
function compressedFontProgram(font: EmbeddedFont, program: Buffer): Buffer {
  if (program === font.program) {
    if (font.programCompressed === undefined) font.programCompressed = deflateSync(program);
    return font.programCompressed;
  }
  return deflateSync(program);
}

/* -------------------------------------------------------------------------- */
/* 文本度量与编码                                                              */
/* -------------------------------------------------------------------------- */

interface LayoutContext {
  /** 嵌入字体；null 表示 base14 Helvetica */
  font: EmbeddedFont | null;
  /** 已完成页面的内容流 */
  pages: string[][];
  /** 当前页内容流 */
  ops: string[];
  /** 光标：距页面顶部的距离（pt） */
  cursor: number;
  /** 嵌入字体路径下真正写出的 glyph id */
  usedGlyphs: Set<number>;
}

/** glyph id 解析：字体里没有的码点用 .notdef（gid 0）兜底，绝不抛错。 */
function glyphFor(font: EmbeddedFont, codePoint: number): number {
  const gid = font.cmap.get(codePoint);
  if (gid === undefined || gid < 0 || gid >= font.glyphCount) return 0;
  return gid;
}

function measureText(ctx: LayoutContext, text: string, size: number, bold: boolean): number {
  const font = ctx.font;
  if (font !== null) {
    let total = 0;
    for (const ch of text) {
      total += font.advanceWidths[glyphFor(font, ch.codePointAt(0) ?? 0)];
    }
    return (total * size) / font.unitsPerEm;
  }
  let total = 0;
  for (const ch of text) total += base14Width(ch.codePointAt(0) ?? 0, bold);
  return (total * size) / 1000;
}

/**
 * 把一行文本编码成 PDF 文本对象里的字符串：
 * base14 → `(...)` 字面量（转义 `( ) \`，不可表示的字符画成 `?`）；
 * 嵌入字体 → `<0048...>`（UTF-16BE 的 glyph id 十六进制串）。
 */
function encodeText(ctx: LayoutContext, text: string): string {
  const font = ctx.font;
  if (font !== null) {
    let hex = '';
    for (const ch of text) {
      const gid = glyphFor(font, ch.codePointAt(0) ?? 0);
      ctx.usedGlyphs.add(gid);
      hex += gid.toString(16).padStart(4, '0');
    }
    return `<${hex}>`;
  }
  let out = '(';
  for (const ch of text) {
    const byte = winAnsiByte(ch.codePointAt(0) ?? 0);
    if (byte === 0x28) out += '\\(';
    else if (byte === 0x29) out += '\\)';
    else if (byte === 0x5c) out += '\\\\';
    else out += String.fromCharCode(byte);
  }
  return `${out})`;
}

/** 以 PDF 坐标（自底向上）的基线写入一行文本。 */
function pushTextLine(
  ctx: LayoutContext,
  ops: string[],
  text: string,
  x: number,
  baseline: number,
  size: number,
  bold: boolean,
  gray: number,
): void {
  if (text === '') return;
  ops.push(
    `${fmt(gray)} g BT ${bold ? '/F2' : '/F1'} ${fmt(size)} Tf 1 0 0 1 ${fmt(x)} ${fmt(baseline)} Tm ${encodeText(ctx, text)} Tj ET`,
  );
}

/** 以「距页面顶部」的位置写入一行文本（颜色必须在 BT/ET 之外设置）。 */
function drawFlowLine(
  ctx: LayoutContext,
  text: string,
  x: number,
  top: number,
  size: number,
  bold: boolean,
  gray: number,
): void {
  pushTextLine(ctx, ctx.ops, text, x, PAGE_HEIGHT - (top + size * BASELINE_RATIO), size, bold, gray);
}

/* -------------------------------------------------------------------------- */
/* 换行（按字符宽度累加）                                                      */
/* -------------------------------------------------------------------------- */

/**
 * 断行单元：CJK / 全角字符逐字成 token，拉丁词整体成 token，空白是唯一的可丢弃断点。
 * 中文没有空格，所以不能按词断行 —— 这里对全角字符逐字累加宽度。
 */
function tokenize(text: string): string[] {
  const tokens: string[] = [];
  let buffer = '';
  for (const ch of text) {
    const codePoint = ch.codePointAt(0) ?? 0;
    if (ch === ' ' || ch === '\t') {
      if (buffer !== '') {
        tokens.push(buffer);
        buffer = '';
      }
      tokens.push(SPACE_TOKEN);
      continue;
    }
    if (isWideChar(codePoint)) {
      if (buffer !== '') {
        tokens.push(buffer);
        buffer = '';
      }
      tokens.push(ch);
      continue;
    }
    buffer += ch;
  }
  if (buffer !== '') tokens.push(buffer);
  return tokens;
}

/** 单个词比整行还宽时按字符硬切（超长 URL / 无空格长串）。 */
function splitToWidth(text: string, maxWidth: number, measure: (value: string) => number): string[] {
  const chunks: string[] = [];
  let current = '';
  for (const ch of text) {
    if (current !== '' && measure(current + ch) > maxWidth) {
      chunks.push(current);
      current = ch;
      continue;
    }
    current += ch;
  }
  if (current !== '') chunks.push(current);
  return chunks;
}

/** 按可用宽度把文本折成多行；显式换行符保持。空文本返回空数组。 */
function wrapText(text: string, maxWidth: number, measure: (value: string) => number): string[] {
  const lines: string[] = [];
  const source = String(text ?? '');
  if (source === '') return lines;

  for (const paragraph of source.split(/\r\n|\r|\n/)) {
    const tokens = tokenize(paragraph);
    let line = '';
    let lineWidth = 0;
    let pendingSpace = false;
    const flush = (): void => {
      if (line !== '') lines.push(line);
      line = '';
      lineWidth = 0;
      pendingSpace = false;
    };

    for (const token of tokens) {
      if (token === SPACE_TOKEN) {
        if (line !== '') pendingSpace = true;
        continue;
      }
      const piece = pendingSpace && line !== '' ? ` ${token}` : token;
      const width = measure(piece);
      if (lineWidth + width <= maxWidth || line === '') {
        if (line === '' && width > maxWidth) {
          const chunks = splitToWidth(token, maxWidth, measure);
          for (let i = 0; i < chunks.length - 1; i += 1) lines.push(chunks[i]);
          line = chunks[chunks.length - 1];
          lineWidth = measure(line);
          pendingSpace = false;
          continue;
        }
        line += piece;
        lineWidth += width;
        pendingSpace = false;
        continue;
      }
      flush();
      if (width > maxWidth) {
        const chunks = splitToWidth(token, maxWidth, measure);
        for (let i = 0; i < chunks.length - 1; i += 1) lines.push(chunks[i]);
        line = chunks[chunks.length - 1];
        lineWidth = measure(line);
        continue;
      }
      line = token;
      lineWidth = width;
    }
    flush();
  }
  return lines;
}

/* -------------------------------------------------------------------------- */
/* 分页与排版原语                                                              */
/* -------------------------------------------------------------------------- */

function createContext(font: EmbeddedFont | null): LayoutContext {
  return { font, pages: [], ops: [], cursor: CONTENT_TOP, usedGlyphs: new Set<number>() };
}

function newPage(ctx: LayoutContext): void {
  ctx.pages.push(ctx.ops);
  ctx.ops = [];
  ctx.cursor = CONTENT_TOP;
}

/** 需要 height 高度时确保当前页放得下，否则翻页（空白新页不重复翻页）。 */
function ensureSpace(ctx: LayoutContext, height: number): void {
  if (ctx.cursor > CONTENT_TOP && ctx.cursor + height > CONTENT_BOTTOM) newPage(ctx);
}

function drawRule(ctx: LayoutContext): void {
  const y = PAGE_HEIGHT - ctx.cursor;
  ctx.ops.push(
    `${fmt(GRAY_RULE)} G ${fmt(LINE_WIDTH_THIN)} w ${fmt(MARGIN)} ${fmt(y)} m ${fmt(MARGIN + CONTENT_WIDTH)} ${fmt(y)} l S`,
  );
}

/* -------------------------------------------------------------------------- */
/* 块级渲染                                                                    */
/* -------------------------------------------------------------------------- */

function renderHeading(ctx: LayoutContext, heading: string): void {
  const measure = (value: string): number => measureText(ctx, value, SIZE_HEADING, true);
  const lines = wrapText(heading, CONTENT_WIDTH, measure);
  if (lines.length === 0) return;
  ctx.cursor += GAP_HEADING_BEFORE;
  ensureSpace(ctx, HEIGHT_HEADING + HEIGHT_BODY);
  for (const line of lines) {
    ensureSpace(ctx, HEIGHT_HEADING);
    drawFlowLine(ctx, line, MARGIN, ctx.cursor, SIZE_HEADING, true, GRAY_HEADING);
    ctx.cursor += HEIGHT_HEADING;
  }
  ctx.cursor += GAP_HEADING_AFTER;
}

function renderParagraph(ctx: LayoutContext, paragraph: string): void {
  const measure = (value: string): number => measureText(ctx, value, SIZE_BODY, false);
  const lines = wrapText(paragraph, CONTENT_WIDTH, measure);
  if (lines.length === 0) return;
  for (const line of lines) {
    ensureSpace(ctx, HEIGHT_BODY);
    drawFlowLine(ctx, line, MARGIN, ctx.cursor, SIZE_BODY, false, GRAY_BODY);
    ctx.cursor += HEIGHT_BODY;
  }
  ctx.cursor += GAP_PARAGRAPH;
}

function renderBullet(ctx: LayoutContext, bullet: string): void {
  const prefix = '• ';
  const prefixWidth = measureText(ctx, prefix, SIZE_BODY, false);
  const measure = (value: string): number => measureText(ctx, value, SIZE_BODY, false);
  const lines = wrapText(`${prefix}${bullet}`, CONTENT_WIDTH, measure);
  if (lines.length === 0) return;
  lines.forEach((line, index) => {
    ensureSpace(ctx, HEIGHT_BODY);
    drawFlowLine(ctx, line, MARGIN + (index === 0 ? 0 : prefixWidth), ctx.cursor, SIZE_BODY, false, GRAY_BODY);
    ctx.cursor += HEIGHT_BODY;
  });
  ctx.cursor += GAP_BULLET;
}

/** 按内容权重分配列宽（全角按 2 个单元估算，夹在上下限内）。 */
function columnWidths(columns: string[], rows: PdfCell[][]): number[] {
  const weights = columns.map((column, index) => {
    let maxUnits = unitsOf(column);
    for (const row of rows) maxUnits = Math.max(maxUnits, unitsOf(cellText(row[index] ?? null)));
    return Math.min(Math.max(maxUnits, COLUMN_WEIGHT_MIN), COLUMN_WEIGHT_MAX);
  });
  const total = weights.reduce((sum, weight) => sum + weight, 0);
  if (total <= 0) return columns.map(() => CONTENT_WIDTH / columns.length);
  return weights.map((weight) => (CONTENT_WIDTH * weight) / total);
}

function rowHeight(cellLines: string[][]): number {
  let maxLines = 1;
  for (const lines of cellLines) maxLines = Math.max(maxLines, lines.length);
  return maxLines * HEIGHT_TABLE + CELL_PADDING_Y * 2;
}

function drawTableRow(
  ctx: LayoutContext,
  top: number,
  widths: number[],
  cellLines: string[][],
  header: boolean,
): void {
  const height = rowHeight(cellLines);
  const bottom = PAGE_HEIGHT - top - height;
  const totalWidth = widths.reduce((sum, width) => sum + width, 0);
  if (header) {
    ctx.ops.push(
      `${fmt(GRAY_TABLE_HEADER_BG)} g ${fmt(MARGIN)} ${fmt(bottom)} ${fmt(totalWidth)} ${fmt(height)} re f`,
    );
  }
  ctx.ops.push(`${fmt(GRAY_TABLE_BORDER)} G ${fmt(LINE_WIDTH_THIN)} w`);
  let x = MARGIN;
  for (let column = 0; column < cellLines.length; column += 1) {
    const width = widths[column];
    ctx.ops.push(`${fmt(x)} ${fmt(bottom)} ${fmt(width)} ${fmt(height)} re S`);
    const lines = cellLines[column];
    for (let line = 0; line < lines.length; line += 1) {
      const baseline = bottom + height - CELL_PADDING_Y - SIZE_TABLE * BASELINE_RATIO - line * HEIGHT_TABLE;
      pushTextLine(
        ctx,
        ctx.ops,
        lines[line],
        x + CELL_PADDING_X,
        baseline,
        SIZE_TABLE,
        header,
        header ? GRAY_HEADING : GRAY_BODY,
      );
    }
    x += width;
  }
}

function renderTable(ctx: LayoutContext, table: PdfTableSpec): void {
  const columns = (Array.isArray(table.columns) ? table.columns : []).map((column) => cellText(column));
  if (columns.length === 0) return;
  const rows = Array.isArray(table.rows) ? table.rows.map((row) => (Array.isArray(row) ? row : [])) : [];

  const name = (table.name ?? '').trim();
  if (name !== '') {
    const lines = wrapText(name, CONTENT_WIDTH, (value) => measureText(ctx, value, SIZE_TABLE_NAME, true));
    for (const line of lines) {
      ensureSpace(ctx, HEIGHT_TABLE_NAME);
      drawFlowLine(ctx, line, MARGIN, ctx.cursor, SIZE_TABLE_NAME, true, GRAY_HEADING);
      ctx.cursor += HEIGHT_TABLE_NAME;
    }
    ctx.cursor += GAP_TABLE_NAME;
  }

  const widths = columnWidths(columns, rows);
  const innerWidths = widths.map((width) => Math.max(20, width - CELL_PADDING_X * 2));
  const headerLines = columns.map((column, index) =>
    wrapText(column, innerWidths[index], (value) => measureText(ctx, value, SIZE_TABLE, true)),
  );
  const bodyLines = rows.map((row) =>
    columns.map((_, index) =>
      wrapText(cellText(row[index] ?? null), innerWidths[index], (value) =>
        measureText(ctx, value, SIZE_TABLE, false),
      ),
    ),
  );

  const headerHeight = rowHeight(headerLines);
  const firstRowHeight = bodyLines.length > 0 ? rowHeight(bodyLines[0]) : 0;
  ensureSpace(ctx, headerHeight + firstRowHeight);

  drawTableRow(ctx, ctx.cursor, widths, headerLines, true);
  ctx.cursor += headerHeight;

  for (const cellLines of bodyLines) {
    const height = rowHeight(cellLines);
    if (ctx.cursor + height > CONTENT_BOTTOM) {
      newPage(ctx);
      drawTableRow(ctx, ctx.cursor, widths, headerLines, true); // 新页重复表头
      ctx.cursor += headerHeight;
    }
    drawTableRow(ctx, ctx.cursor, widths, cellLines, false);
    ctx.cursor += height;
  }
  ctx.cursor += GAP_TABLE;
}

function renderDocument(doc: PdfDocSpec, ctx: LayoutContext): void {
  const title = (doc.title ?? '').trim();
  const subtitle = (doc.subtitle ?? '').trim();

  if (title !== '') {
    const lines = wrapText(title, CONTENT_WIDTH, (value) => measureText(ctx, value, SIZE_TITLE, true));
    for (const line of lines) {
      drawFlowLine(ctx, line, MARGIN, ctx.cursor, SIZE_TITLE, true, GRAY_TITLE);
      ctx.cursor += HEIGHT_TITLE;
    }
  }
  if (subtitle !== '') {
    const lines = wrapText(subtitle, CONTENT_WIDTH, (value) => measureText(ctx, value, SIZE_SUBTITLE, false));
    for (const line of lines) {
      drawFlowLine(ctx, line, MARGIN, ctx.cursor, SIZE_SUBTITLE, false, GRAY_SUBTITLE);
      ctx.cursor += HEIGHT_SUBTITLE;
    }
  }
  if (title !== '' || subtitle !== '') {
    ctx.cursor += 6;
    drawRule(ctx);
    ctx.cursor += 14;
  }

  const sections = Array.isArray(doc.sections) ? doc.sections : [];
  for (const section of sections) {
    const heading = (section.heading ?? '').trim();
    if (heading !== '') renderHeading(ctx, heading);
    const paragraphs = Array.isArray(section.paragraphs) ? section.paragraphs : [];
    for (const paragraph of paragraphs) renderParagraph(ctx, String(paragraph ?? ''));
    const bullets = Array.isArray(section.bullets) ? section.bullets : [];
    for (const bullet of bullets) renderBullet(ctx, String(bullet ?? ''));
    if (section.table !== undefined && section.table !== null) renderTable(ctx, section.table);
  }
}

function appendFooters(ctx: LayoutContext, footer: string, watermark: string): void {
  const total = ctx.pages.length;
  ctx.pages.forEach((ops, index) => {
    if (footer !== '') {
      pushTextLine(ctx, ops, footer, MARGIN, FOOTER_BASELINE, SIZE_FOOTER, false, GRAY_FOOTER);
    }
    if (watermark !== '') {
      const width = measureText(ctx, watermark, SIZE_FOOTER, false);
      pushTextLine(ctx, ops, watermark, (PAGE_WIDTH - width) / 2, FOOTER_BASELINE, SIZE_FOOTER, false, GRAY_FOOTER);
    }
    const label = `${index + 1} / ${total}`;
    const width = measureText(ctx, label, SIZE_FOOTER, false);
    pushTextLine(ctx, ops, label, PAGE_WIDTH - MARGIN - width, FOOTER_BASELINE, SIZE_FOOTER, false, GRAY_FOOTER);
  });
}

/* -------------------------------------------------------------------------- */
/* 字体对象（base14 / 嵌入）                                                   */
/* -------------------------------------------------------------------------- */

function base14FontObject(baseFont: string, bold: boolean): Buffer {
  return bufferOf(
    `<< /Type /Font /Subtype /Type1 /BaseFont /${baseFont} /Encoding /WinAnsiEncoding ` +
      `/FirstChar 32 /LastChar 255 /Widths ${base14WidthArray(bold)} >>`,
  );
}

/** /W 稀疏宽度表：连续 glyph 合成 range，单位换算到 1/1000 em。 */
function embeddedWidthArray(font: EmbeddedFont, used: Set<number>): string {
  const gids = [...used].sort((a, b) => a - b);
  const groups: string[] = [];
  let start = -1;
  let widths: string[] = [];
  let previous = -2;
  const flush = (): void => {
    if (start >= 0) groups.push(`${start} [${widths.join(' ')}]`);
  };
  for (const gid of gids) {
    const advance = font.advanceWidths[gid];
    const width = Math.round((advance * 1000) / font.unitsPerEm);
    if (start >= 0 && gid === previous + 1) {
      widths.push(String(width));
      previous = gid;
      continue;
    }
    flush();
    start = gid;
    widths = [String(width)];
    previous = gid;
  }
  flush();
  return `[ ${groups.join(' ')} ]`;
}

/** ToUnicode CMap：glyph id → Unicode（每 100 条一个 beginbfchar 块）。 */
function toUnicodeCMap(font: EmbeddedFont, used: Set<number>): string {
  const entries: string[] = [];
  for (const gid of [...used].sort((a, b) => a - b)) {
    const codePoint = font.glyphToCodePoint.get(gid);
    if (codePoint === undefined) continue;
    entries.push(`<${utf16Hex(gid)}> <${utf16Hex(codePoint)}>`);
  }
  const blocks: string[] = [];
  for (let i = 0; i < entries.length; i += 100) {
    const slice = entries.slice(i, i + 100);
    blocks.push([`${slice.length} beginbfchar`, ...slice, 'endbfchar'].join('\n'));
  }
  if (blocks.length === 0 || entries.length === 0) blocks.push('0 beginbfchar', 'endbfchar');
  return [
    '/CIDInit /ProcSet findresource begin',
    '12 dict begin',
    'begincmap',
    '/CIDSystemInfo << /Registry (Adobe) /Ordering (UCS) /Supplement 0 >> def',
    `/CMapName /${font.postScriptName}-UCS def`,
    '/CMapType 2 def',
    '1 begincodespacerange',
    '<0000> <FFFF>',
    'endcodespacerange',
    ...blocks,
    'endcmap',
    'CMapName currentdict /CMap defineresource pop',
    'end',
    'end',
  ].join('\n');
}

function streamObject(dict: string, data: Buffer): Buffer {
  const head = dict === '' ? `<< /Length ${data.length} >>` : `<< ${dict} /Length ${data.length} >>`;
  return Buffer.concat([bufferOf(`${head}\nstream\n`), data, bufferOf('\nendstream')]);
}

/* -------------------------------------------------------------------------- */
/* PDF 组装                                                                    */
/* -------------------------------------------------------------------------- */

function buildPdfFile(objects: Buffer[], rootRef: number, infoRef: number): Buffer {
  const chunks: Buffer[] = [];
  let offset = 0;
  const push = (data: Buffer): void => {
    chunks.push(data);
    offset += data.length;
  };

  // 二进制标记行（% 注释）让工具可靠识别这是二进制 PDF
  push(bufferOf('%PDF-1.7\n%\u00e2\u00e3\u00cf\u00d3\n'));

  const offsets: number[] = [];
  objects.forEach((body, index) => {
    offsets.push(offset);
    push(bufferOf(`${index + 1} 0 obj\n`));
    push(body);
    push(bufferOf('\nendobj\n'));
  });

  const xrefOffset = offset;
  const xref: string[] = [`xref\n0 ${objects.length + 1}\n`, '0000000000 65535 f \n'];
  for (const entry of offsets) xref.push(`${String(entry).padStart(10, '0')} 00000 n \n`);
  push(bufferOf(xref.join('')));

  push(
    bufferOf(
      `trailer\n<< /Size ${objects.length + 1} /Root ${rootRef} 0 R /Info ${infoRef} 0 R >>\n` +
        `startxref\n${xrefOffset}\n%%EOF\n`,
    ),
  );

  return Buffer.concat(chunks);
}

/** Info 字典里的文本串：纯 ASCII 用字面量，否则 UTF-16BE（带 BOM）。 */
function pdfTextString(text: string): string {
  for (const ch of text) {
    const codePoint = ch.codePointAt(0) ?? 0;
    if (codePoint < 0x20 || codePoint > 0x7e) {
      return `<feff${[...text].map((item) => utf16Hex(item.codePointAt(0) ?? 0)).join('')}>`;
    }
  }
  const escaped = text.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
  return `(${escaped})`;
}

/** 收集文档里所有可见文本（用于判断是否需要 Unicode 字体）。 */
function collectText(doc: PdfDocSpec, watermark: string): string {
  const parts: string[] = [doc.title ?? '', doc.subtitle ?? '', watermark];
  const sections = Array.isArray(doc.sections) ? doc.sections : [];
  for (const section of sections) {
    parts.push(section.heading ?? '');
    for (const paragraph of Array.isArray(section.paragraphs) ? section.paragraphs : []) {
      parts.push(String(paragraph ?? ''));
    }
    for (const bullet of Array.isArray(section.bullets) ? section.bullets : []) {
      parts.push(String(bullet ?? ''));
    }
    const table = section.table;
    if (table !== undefined && table !== null) {
      parts.push(table.name ?? '');
      for (const column of Array.isArray(table.columns) ? table.columns : []) parts.push(cellText(column));
      const rows = Array.isArray(table.rows) ? table.rows : [];
      for (const row of rows) {
        if (!Array.isArray(row)) continue;
        for (const cell of row) parts.push(cellText(cell));
      }
    }
  }
  return parts.join('\n');
}

/** 解析这次渲染用哪条字体路径（null → base14）。任何失败都回落 base14，绝不抛错。 */
function resolveFont(options: WritePdfOptions): EmbeddedFont | null {
  if (options.font === null) return null;
  const info = options.font ?? discoverPdfFont(options.fontPath);
  if (info === null || info === undefined) return null;
  const fontPath = typeof info.path === 'string' ? info.path : options.fontPath;
  if (fontPath === undefined || fontPath.trim() === '') return null;
  return loadFont(fontPath);
}

/* -------------------------------------------------------------------------- */
/* 公共 API                                                                    */
/* -------------------------------------------------------------------------- */

interface FontFilePlan {
  /** FontFile2 的原始（未压缩）字体程序 */
  program: Buffer;
  /** 子集化统计；整份嵌入时为 null */
  subset: SubsetStats | null;
}

/** 决定这次嵌入哪份字体程序：优先子集化，任何异常都回退成整份嵌入（宁大勿坏）。 */
function planFontFile(font: EmbeddedFont, usedGids: Set<number>, subsetFont: boolean): FontFilePlan {
  if (subsetFont) {
    try {
      const result = subsetFontProgram(font.program, usedGids);
      return { program: result.program, subset: result.stats };
    } catch {
      return { program: font.program, subset: null };
    }
  }
  return { program: font.program, subset: null };
}

/**
 * 生成 PDF。
 * - 有可用 TrueType 字体 → 嵌入并支持完整 Unicode（含中文）；默认只嵌入用到的字形（子集化）
 * - 无字体（font: null 或未发现）→ base14 Helvetica；此时若内容是纯 Latin-1 仍正常出图，
 *   并把 requiresUnicodeFont 置为 true 表示「内容有它渲染不了的字」
 */
export function writePdf(doc: PdfDocSpec, options?: WritePdfOptions): PdfWriteResult {
  const opts: WritePdfOptions = options ?? {};
  const source: PdfDocSpec = doc ?? { sections: [] };
  const footer = (source.footer ?? '').trim();
  const watermark = (opts.watermark ?? '').trim();
  const font = resolveFont(opts);

  const ctx = createContext(font);
  renderDocument(source, ctx);
  ctx.pages.push(ctx.ops);
  appendFooters(ctx, footer, watermark);

  const pageCount = ctx.pages.length;
  const contentBuffers = ctx.pages.map((ops) => bufferOf(`${ops.join('\n')}\n`));

  // 字体程序：默认子集化，任何异常都回退成整份嵌入（宁大勿坏）
  const fontFile = font === null ? null : planFontFile(font, ctx.usedGlyphs, opts.subsetFont !== false);
  const embedded = font !== null && fontFile !== null;

  const catalogRef = 1;
  const pagesRef = 2;
  const pageRef = (index: number): number => 3 + index;
  const contentRef = (index: number): number => 3 + pageCount + index;
  const fontBase = 3 + pageCount * 2;
  const infoRef = embedded ? fontBase + 5 : fontBase + 2;
  const regularFontRef = fontBase;
  const boldFontRef = embedded ? fontBase : fontBase + 1;

  const objects: Buffer[] = [];
  objects.push(bufferOf(`<< /Type /Catalog /Pages ${pagesRef} 0 R >>`));
  const kids = ctx.pages.map((_, index) => `${pageRef(index)} 0 R`).join(' ');
  objects.push(bufferOf(`<< /Type /Pages /Kids [${kids}] /Count ${pageCount} >>`));

  for (let index = 0; index < pageCount; index += 1) {
    const resources =
      `<< /Font << /F1 ${regularFontRef} 0 R /F2 ${boldFontRef} 0 R >> ` +
      `/ProcSet [/PDF /Text] >>`;
    objects.push(
      bufferOf(
        `<< /Type /Page /Parent ${pagesRef} 0 R /MediaBox [0 0 ${fmt(PAGE_WIDTH)} ${fmt(PAGE_HEIGHT)}] ` +
          `/Resources ${resources} /Contents ${contentRef(index)} 0 R >>`,
      ),
    );
  }
  for (const content of contentBuffers) objects.push(streamObject('', content));

  if (font === null || fontFile === null) {
    objects.push(base14FontObject('Helvetica', false));
    objects.push(base14FontObject('Helvetica-Bold', true));
  } else {
    // Type0 字体对象号就是 regularFontRef（fontBase），/F1 与 /F2 指向同一个 Type0 对象
    const cidRef = fontBase + 1;
    const descriptorRef = fontBase + 2;
    const fontFileRef = fontBase + 3;
    const toUnicodeRef = fontBase + 4;
    const name = font.postScriptName;
    const bbox = font.bbox.map((value) => Math.round((value * 1000) / font.unitsPerEm));

    objects.push(
      bufferOf(
        `<< /Type /Font /Subtype /Type0 /BaseFont /${name} /Encoding /Identity-H ` +
          `/DescendantFonts [${cidRef} 0 R] /ToUnicode ${toUnicodeRef} 0 R >>`,
      ),
    );
    objects.push(
      bufferOf(
        `<< /Type /Font /Subtype /CIDFontType2 /BaseFont /${name} ` +
          '/CIDSystemInfo << /Registry (Adobe) /Ordering (Identity) /Supplement 0 >> ' +
          `/FontDescriptor ${descriptorRef} 0 R /DW 1000 /W ${embeddedWidthArray(font, ctx.usedGlyphs)} ` +
          '/CIDToGIDMap /Identity >>',
      ),
    );
    objects.push(
      bufferOf(
        `<< /Type /FontDescriptor /FontName /${name} /Flags 4 ` +
          `/FontBBox [${bbox.join(' ')}] /ItalicAngle 0 /Ascent ${font.ascender} /Descent ${font.descender} ` +
          `/CapHeight ${font.capHeight} /StemV 80 /FontFile2 ${fontFileRef} 0 R >>`,
      ),
    );
    objects.push(
      streamObject(
        `/Length1 ${fontFile.program.length} /Filter /FlateDecode`,
        compressedFontProgram(font, fontFile.program),
      ),
    );
    objects.push(streamObject('', bufferOf(toUnicodeCMap(font, ctx.usedGlyphs))));
  }

  const infoParts = ['/Producer (RoveFrame AI COO PDF Writer)'];
  const title = (source.title ?? '').trim();
  if (title !== '') infoParts.push(`/Title ${pdfTextString(title)}`);
  objects.push(bufferOf(`<< ${infoParts.join(' ')} >>`));

  return {
    data: buildPdfFile(objects, catalogRef, infoRef),
    mime: PDF_MIME,
    ext: PDF_EXT,
    font: font === null ? 'helvetica' : 'embedded',
    fontPath: font === null ? undefined : font.path,
    pageCount,
    requiresUnicodeFont: font === null && needsUnicodeFont(collectText(source, watermark)),
    subset: fontFile === null ? null : fontFile.subset,
  };
}
